### ISSUE TITLE
￼ getting => Failed to wait for "webview:protonmail" service provider initialization

### ISSUE THREAD

**Issue by ghost** [vladimiry/ElectronMail#126]
I started getting this error on version 3.1.0.  It shows the login page but does not even attempt to fill the username field.

Note that I have two profiles, and the error is only for one account in one of the profiles.  A separate account in that same profile as the the broken account works fine.

(edit)

Problem went away.  Out of the blue it works again.  Maybe PM was down momentarily.

**Comment by libBletchley** [comment]
Actually I saw this error again, but this time it seems my WAN connection died.  So this is apparently the error msg users will see when they lose connectivity.

**Comment by libBletchley** [comment]
Today I got this error:

Failed to wait for "webview:tutanota" service provider initialization

And ironically, it seems to have blocked me from logging into protonmail.  I clicked on a Protonmail tab, got a Tutanota error, no protonmail error, and yet my creds did not get filled to make a login attempt.

**Comment by vladimiry** [comment]
If there is no internet connection the app won't start waiting for service provider initialization. Being or getting online triggers service initialization and if the connection gets down even for a moment you will get such error. I think this might be related to the connections drops happening using Tor.

**Comment by libBletchley** [comment]
It's happened a couple more times.  I get the error saying something is wrong with tutanota, but in fact there is no problem with tutanota, the problem is with protonmail.  

Another problem:  The tutanota padlock does not open even though tutanota successfully logged in.  So the padlock is wrong.  This is the whole sequence of things:

1. launch EM and enter master password
1. all tabs are configured *not* to login, so there should be no connection attempts being made at this point
1. red popup saying `Failed to wait for "webview:tutanota" service provider initialization`
1. i click on a **protonmail** tab.  Nothing happens
1. i click on a **tutanota** tab. Login works.
1. i click on the **protonmail** tab again, and still nothing happens
1. i notice the tutanota padlock is closed, which makes me think tutanota lost connection
1. i click the tutanota tab, and it's still showing my inbox even though the padlock is closed.

Seems there are 3 bugs here:
* connection attempted even though no tab selected
* error reports the wrong server as having the problem
* padlock shows the wrong state

**Comment by vladimiry** [comment]
There will be a need to reproduce the possible issue at my side in order to fix them but it's not yet the case. I still tend to think that it's specific to your environment (tor/whonix/etc). I'm reopening the issue but I'm not going to test the case running tor/whonix in the near future.

> Failed to wait for "webview:tutanota" service provider initialization

Padlock won't work due to the above error. Means the communication channel between the app and account has not been initialized. So it's expected behavior.

**Comment by vladimiry** [comment]
Here is some explanation of how communication with email provider's account is being initialized and performed by the app.

Each time the app calls some action supposed to be performed at the email provider's account side it first resolves the API client by calling `webViewClient` method:
https://github.com/vladimiry/ElectronMail/blob/063b49ac9c01dc2b7becd7b84c93b3bb3c6d1bf0/src/web/src/app/_core/electron.service.ts#L58
This process involves checking the network availability before calling the `ping` enpoint: https://github.com/vladimiry/ElectronMail/blob/063b49ac9c01dc2b7becd7b84c93b3bb3c6d1bf0/src/web/src/app/_core/electron.service.ts#L68
So each time the app calls some action to be performed at the email provider's account side it first waits for online status as normally any custom action to be performed at the email provider's account side requires an internet connection to be established. Then the app calls `ping` action and only after that it calls the original action. Failed `ping` action calling with `Failed to wait for "webview:tutanota/protonmail" service provider initialization`-like error message means that the communication channel has not been setup for some reason.

**Comment by vladimiry** [comment]
Closing due to the inactivity and because the OP went @ghost mode :smile:
