### ISSUE TITLE
Option to hide the top bar when only one email provider

### ISSUE THREAD

**Issue by skewty** [vladimiry/ElectronMail#128]
I only have one email account and don't require the read count badge.  Is there any way to remove that bar at the top?

I was hoping to just press F12 and set the div to hidden..  but F12 doesn't do anything :)

**Comment by vladimiry** [comment]
The app doesn't allow hiding the buttons bar and enabling such option is not planned. The button bar, by the way, holds not only the accounts buttons but also the settings button including the related dropdown menu.

**Comment by vladimiry** [comment]
Closing as resolved.

**Comment by vladimiry** [comment]
It's becoming more demanding so reopening.

**Comment by vladimiry** [comment]
The feature is on the way.

**Comment by vladimiry** [comment]
Can someone try [this](https://www.dropbox.com/sh/xxngvxsykh1a4y5/AAC6cljCNDfdtM-cRXVV8d2Ha?dl=0&lst=) build and confirm that it resolves the issue? The controls bar visibility can be toggled by clicking the respective option in the general settings or hitting F12 key. Besides the tray menu has got "Options" item added so if you have hidden the controls bar and forgot the hotkey to get it back you could reach the options modal via the tray menu.

![recording](https://user-images.githubusercontent.com/1560781/59600320-85fa0900-9109-11e9-83bc-bb9e42bf4e2d.gif)

Why named controls bar but not the top bar? Because it can also be located at the left side, here is the option that toggles the view mode:

![recording2](https://user-images.githubusercontent.com/1560781/59600717-aaa2b080-910a-11e9-92ae-84b85fa4e443.gif)

CC @skewty, @ByteEnable.

**Comment by vladimiry** [comment]
The feature has been enabled with [v3.6.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.6.0) release.
