### ISSUE TITLE
Local storege fails if account contains non-decryptable email.

### ISSUE THREAD

**Issue by nloomans** [vladimiry/ElectronMail#129]
## Steps to reproduce

 1. Send an email to your self using a PGP Key your ProtonMail has not been setup to decrypt.
 2. Enable local storage
 3. The following error will now popup: _Error decrypting message: Session key decryption failed_

This is how such an email is shown when viewing it within the web client:

![2019-04-10-212837_1920x1080_scrot](https://user-images.githubusercontent.com/7829481/55908290-4f6bb380-5bd9-11e9-96d0-c14d323002bd.png)

## Expected behavior

Instead of failing to enable local storage entirely, it would be nice if ElectronMail just ignored such emails.

## Workaround

1. Disable local store
2. Delete the email (not just trash it!) which contains un-decryptable content.
3. Enable local storage

(The enabling and disable part might not be necessary)

**Comment by vladimiry** [comment]
Thanks for the thoughtful report. There will be a need to unambiguously distinguish the decryption error due to the absence of PGP key from other types of errors so the app skips only one specific error. So there is a need to, first of all, debugging the case in order to determine if it's feasible to catch the exact error since the same error type might potentially be thrown by protonmail/pgp for different cases.

**Comment by vladimiry** [comment]
I was thinking about how to solve the body decryption issues once and forever and not hurting the UX in along with that and I think I came up with a unified solution that will even enhance the UX:
- The app won't stop the emails downloading process regardless of the body decrypting result.
- If any kind of error occurred during the [body decryption process](https://github.com/ProtonMail/WebClient/blob/62cf7f80301f376b429fec44d25025829f172c23/src/app/message/factories/messageModel.js#L388) the app will set the body to empty but will also add to the email the `bodyDecryptiongError` property with at least the following properties: error message, error stack trace, date, app version. This is a better idea than skipping/ignoring the problematic email.
- If a user opens the email with filled `bodyDecryptiongError` property in the database view mode the app will show the `re-download` button instead of the body content. The app will also display near to the button the original error happened during decryption. So there will be a way to individually for email re-download the body content without publishing a new app release in the case of for example upstream issue like this [one](https://github.com/ProtonMail/WebClient/issues/146) got fixed.
- Emails with filled `bodyDecryptiongError` property will get the respective indication in the list view of the database view mode. It also won't hurt to add the respective filter to the full-text search criteria list.
- Exported to EML files emails with filled `bodyDecryptiongError` property will get the original decryption error message instead of the body content.

So having the described idea implemented the app won't face a blockers happening due to the decryption problems during the emails bootstrap fetch process.

This is going to be a unified solution for the problem so there will be no need to unambiguously distinguish the decryption error type as I wrote in the previous message.

@nloomans of course this will solve the original issue.

@ihubgit this is going to solve the issue raised by you [here](https://github.com/vladimiry/ElectronMail/issues/112) without a need to wait for the [upstream issue](https://github.com/ProtonMail/WebClient/issues/146) resolving. So you will be able to safely enable the [local database](https://user-images.githubusercontent.com/1560781/51189497-382a6c00-18f1-11e9-9b9a-baa63f0c0ff4.gif) option.

PS all of that is protonmail related only.

**Comment by vladimiry** [comment]
@nloomans can you try [pre 3.2.0](https://www.dropbox.com/sh/t9nyqi8xn5ukwra/AAAU2nlH6eLxnMt9Ydrj6lRua?dl=0&lst=) build?

It works as described in the previous message:
![body-decryption-failed](https://user-images.githubusercontent.com/1560781/56080813-562f3c00-5e0e-11e9-81c4-ef230a2d65ac.gif)

**Comment by nloomans** [comment]
@vladimiry I have tested the build and it works perfectly! Both with an partial update and after removing `database.bin`

Thanks!

**Comment by vladimiry** [comment]
Thanks for testing. A new release is going to be published soon.

**Comment by vladimiry** [comment]
The improvement has been released with [3.2.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.2.0) version.
