### ISSUE TITLE
Question: Is Electronmail Encryption Enabled By Default?

### ISSUE THREAD

**Issue by trymeouteh** [vladimiry/ElectronMail#137]
Is the encryption enabled by default when you install it and setup a master password? Or do I need to enable it in the settings to have encryption?

**Comment by joshirio** [comment]
Yes it is, the local storage is encrypted with the master password. Note that if you enable the "keep me signed in" feature the master password will be stored into your sytem's keyring which means that the data will still be encrypted but a bit less secure, since everyone with your login access, and maybe other programs that have access to this keyring, could potentially read your master password.

**Comment by vladimiry** [comment]
All the sensitive data is encrypted by default and there is no way to turn off the encryption. But you can change in the settings the key derivation function, key derivation work factor, and encryption algorithm.

@joshirio totally correct.
