### ISSUE TITLE
Get back update check

### ISSUE THREAD

**Issue by vladimiry** [vladimiry/ElectronMail#159]
Going to get back update check. But this time it will work for all the installation packages types and will only check the update and notify, no automatic downloading and installing.

The code is going to just scan the https://api.github.com/repos/vladimiry/ElectronMail/releases on app start and notify if there are new releases. There will be a way to turn the feature off.

**Comment by joshirio** [comment]
I have a few people (non technical) that use ElectronMail and I have to always tell them that an update is available because they don't follow GitHub, they have even difficulties finding the project page and the correct release page.

So this is a great idea and I'd like to suggest adding an action to the notification that takes the user directly to the new version releases page. So they can upgrade directly with one click.

Another consideration is if app store like distributions should have this, for example snaps are updated automatically, if a user would get such notification he would go on GitHub and maybe download the update for a different package format like .deb and then wondering why his settings are gone, instead of receiving the upgrade through snapd.

**Comment by vladimiry** [comment]
Work in progress demo:
![up1-min](https://user-images.githubusercontent.com/1560781/59197456-0cf33280-8b9a-11e9-8495-2bbdc78018af.gif)
![up2-min](https://user-images.githubusercontent.com/1560781/59197457-0d8bc900-8b9a-11e9-8f40-65a5bc3c6aeb.gif)

**Comment by vladimiry** [comment]
I'm considering removing a hint near the update check option in the setting modal. Removing a hint implies that the feature works the same way for all the package types or doesn't work at all for some package types. So @joshirio do you think the app could do either of below points instead of the initially proposed option of ignoring the update check for a Snap package:
- The option is enabled by default for all the package types except a Snap package. But if a user explicitly enables the option then the feature works the same way as for other package types.
- The app not only ignores the update check for a Snap package but also hides the update check option from the settings so it's like there is no such feature at all for a Snap package.

**Comment by joshirio** [comment]
Let's see, I think either option is fine.

* Option A. This makes sense because non-tech users are unlikely to touch advance settings, so that if they install from snap store they usually know that all snaps are updated automatically and in my case I preconfigure the client for my folks, who then just launch the app and read the mails. Allowing this option is also a feature for the advanced user who wants to be notified about updates, even on snap, to make sure the snap package doesn't fall out of the update cycle.
* Option B. This is the usual way for software to deal with app stores and repositories, where the update configuration in the settings is just grayed out. Pro: less confusing for people who wonder if they receive automatically updates through snap or if they have to go to the website and download the .snap package manually. Though this option in option A is not enabled by default, so not sure if that is really an issue then. Downside: no way to know if the snap is outdated.

I guess you can pick the one that has less maintenance and dev overhead or as you wish.

**Comment by vladimiry** [comment]
Thanks for the input. I tend to choose option A.

Besides going to tweak the update check logic a little by making the app only show the update notification if the update is available for the platform the app is being run. So for example, if you are Linux user you don't get the update notification for [v3.4.1](https://github.com/vladimiry/ElectronMail/releases/tag/v3.4.1) as it includes the assets for Windows platform only.

**Comment by vladimiry** [comment]
The [v3.5.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.5.0) release has just been published with the feature included.
