### ISSUE TITLE
Add a deb repository

### ISSUE THREAD

**Issue by Faust30000** [vladimiry/ElectronMail#192]
It would be very convenient if you add a repository for deb distributions. Now constantly need to download a new release from the site, and one of the main advantages of Linux, the update of all components from one Update Manager, is lost.

**Comment by vladimiry** [comment]
Thanks for the input but I'm closing the issue with the same status as similar [RPM-publishing request](https://github.com/vladimiry/ElectronMail/issues/190) got recently closed. Indeed publishing to the repository would ease regular updates but it also incurs the maintenance burden increasing.

I'd suggest taking a look at Snap package/repository. Snap is considered as a more secure installation package option as it comes with built-in isolation capabilities.

**Comment by snkfxx** [comment]
I know this is closed and marked as wontfix, but since it's been two years I thought I'd try and ask again:

Any chance you'd consider making an apt-repository for electronmail? Alternatively, would you consider supporting one if someone was willing to maintain it?

Electronmail's user base has surely grown a lot in the last two years and it would benefit a lot of people if there was a repository.

Thanks for a great app!

**Comment by vladimiry** [comment]
> Any chance you'd consider making an apt-repository for electronmail?

It's still "won't" fix resolution. There are flatpak + snap repositories which available for use on any linux system (I'd in general prefer flatpak).

> Alternatively, would you consider supporting one if someone was willing to maintain it?

I can't prevent someone from creating apt-repository repository. But I won't be listing it in the project's readme nor supporting in any way.

**Comment by vladimiry** [comment]
See #489 for a possible option.
