### ISSUE TITLE
Would Sciter be a better platform?

### ISSUE THREAD

**Issue by skewty** [vladimiry/ElectronMail#197]
https://sciter.com/

Smaller bundle.  Nodejs isn't even a requirement but is hard bundled (Electron) if I am not mistaken.

Perhaps it would also allow for easier integration( #62) .

**Comment by vladimiry** [comment]
- Thorough time-consuming research would need to be performed in order to answer is Sciter capable of handling the need and what it will take to rewrite the app. I'm not goint to jump into such research at the moment.
- Even if Sciter is a technically rich enough tool the community size and amount of existing modules is also a matter.
- One could say Electron is a resource-consuming thing but I'd suggest to compare it with a regular web browser. Opening a new tab with https://mail.protonmail.com/login page in a browser might start a new process that consumes a similar or even higher amount of RAM in comparison with adding a new account to the app.

> Perhaps it would also allow for easier integration(#62).

It's technically feasible to handle #62 with Electron but the work is not being started yet as the feature is not crucial and the implementation is expected to be a somehow sophisticated/hacky.
