### ISSUE TITLE
Won't start on Windows 10

### ISSUE THREAD

**Issue by sondreb** [vladimiry/ElectronMail#202]
I recently reinstalled Windows 10 and hoped that Electron Mail (3.7.1) would start working again there, no luck. In both installation of Window 10, ElectronMail does not want to launch after initial installation and setup. I have added multiple accounts on first launch, then when I try again later, it never starts (doesn't show any UI).

It does start some processes in the background, but it always fails to load complete.

![image](https://user-images.githubusercontent.com/309938/64295621-d9922b00-cf71-11e9-8093-27660169200b.png)

This did not happen on the previous release if I recall correctly. Will attempt a downgrade and see. Thanks!

**Comment by sondreb** [comment]
Same issue if I uninstall 3.7.1 and install 3.7.0, never works even on first launch.

**Comment by vladimiry** [comment]
@electron team released a bunch of new versions already since  3.7.1 app version got released and one of that release includes a fix of window size gets set to 0 or position gets set to -32000 for both coordinates (respective PR is [here](https://github.com/electron/electron/pull/19928)). So I guess that could be your case since you got the processes started but can't see the app window.

- Is the tray icon visible and functional? Like you click "About" and get the respective window displayed and same for the "Open Settings Folder" tray menu item.
- I presume you got bad values saved in `window.bounds` section of the `config.json` file or alternatively there are some errors in `log.log`. So can you attach here or send to the email specified in the `author` section in [package.json](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5) the following files located in `c:\Users\<user>\AppData\Roaming\electron-mail\`?:
  - config.json
  - log.log

If you see a presumably wrong `window.bounds` values in `config.json` you could try fixing them or just remove the file and the app will re create it on new start.

If that is a wrong `window.bounds` values case then even though @electron got fixed the issue in new releases I think I better add some logic that will verify and correct the values when the app starts as they, unfortunately, used to break things quite often.

**Comment by vladimiry** [comment]
If you want to try it, the pre-3.8.0 release with improved app window state restoring is uploaded [here](https://www.dropbox.com/sh/zir8yoz1gclmr2b/AAAaX3urM7Kf2ok0syHxenLUa?dl=0&lst=).

Changes since 3.7.1 release:
- Support automatic logout after a configurable idle period (5b2ef0cade56e0ec0ff4dc5ae26dd4603efd7cad, #196). This is an experimental and disabled by default feature.
  ![idle](https://user-images.githubusercontent.com/1560781/63686223-fb6d0e80-c809-11e9-8ecf-161dd9e6cb69.png)
- Preserve local database mails list view mode in the config file (ed0d0c7). It was already possible before to switch the `plain`/`conversation` view in the local database view mode like shown in the below screenshot but now the chosen value is preserved in the config file and shared between all the accounts. Defaults to `plain`.
  ![peek](https://user-images.githubusercontent.com/1560781/52346314-6868b480-2a30-11e9-8b04-c6abf9f42a6a.gif)
- Make sure the app window is visible after restoring saved state (af1da7317a452ee6438002db0c59be28ced4d7c3, #202).
- Update prepackaged / built-in web clients (b91b3285eeb60b0a535ad5b5778463c926fb3d9f).

**Comment by sondreb** [comment]
Thanks for the awesome support! :-D The tray icon did appear, and made it possible to show the main window. I did attempt to change the "maximized" value in config.json, but it was reset when launching. Thanks again!
