### ISSUE TITLE
Errors which stop update (download offline data)

### ISSUE THREAD

**Issue by joeschmoe1869** [vladimiry/ElectronMail#209]
I just started using Electronmail and trying to set up offline data. Please see screenshots 
There may be duplicates as this has happened 3 separate times since yesterday.

<img width="1369" alt="Screen Shot 2019-11-02 at 1 36 03 PM" src="https://user-images.githubusercontent.com/57276327/68076374-2a63ab80-fd8a-11e9-82b0-4ddbb2865328.png">
<img width="1369" alt="Screen Shot 2019-11-02 at 2 30 52 PM" src="https://user-images.githubusercontent.com/57276327/68076375-2a63ab80-fd8a-11e9-8210-cf28ecf8a4ca.png">
<img width="1369" alt="Screen Shot 2019-11-02 at 12 48 37 PM" src="https://user-images.githubusercontent.com/57276327/68076376-2afc4200-fd8a-11e9-860b-0c70f642426e.png">

**Comment by vladimiry** [comment]
To ensure the consistency of the local database the data validation is taking place. In your case, there is at least one email that doesn't pass the validation due to the empty sender. Currently, the sender is a required field of the email which means the "local store" won't be working for you and so **you better disable the feature** until you either remove the problematic email message or the new app version weakens the data validation.

**Comment by joeschmoe1869** [comment]
Thank you for a very quick response. Nice app and much better than using Bridge and Outlook as Outlook is a memory hog.

**Comment by vladimiry** [comment]
I will consider printing a subject of the email message that doesn't pass the data validation during local data saving so it will be easier to locate this email and remove/correct it. So let's keep the issue open.

**Comment by vladimiry** [comment]
The local database entity validation error message now looks more informative with added mail subject and date, so it's easier to locate the problematic email message.

Here is the message example: 
![error-message](https://user-images.githubusercontent.com/1560781/68422922-24b6fd00-01b2-11ea-94c5-bba515bde694.png)

The change is already in the master branch and will be a part of the next release.
