### ISSUE TITLE
body: {"isString":"body must be a string"}

### ISSUE THREAD

**Issue by nil0x42** [vladimiry/ElectronMail#218]
Hi ! Since 2 weeks i get constant error message appearing frenquently:
```
body: {"isString":"body must be a string"}
```

(v3.8.0)

**Comment by vladimiry** [comment]
This error will only occur if you use Tutanota and have the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option enabled for the account. You can find more details in #180.

The error is expected to happen since Tutanota changed the data model (backed stuff) and a new app version with the fix included has not been released since then (and won't be as Tutanota support to be dropped soon).

If you still want to use Tutanota with ElectronMail you can find a download link to the working 3.8.1 build in [this](https://github.com/vladimiry/ElectronMail/issues/180#issuecomment-551305190) message.
