### ISSUE TITLE
Error in desktop client when a new email is added via the web client

### ISSUE THREAD

**Issue by lyndsysimon** [vladimiry/ElectronMail#228]
I added an email address from the ProtonMail web interface recently while on my desktop PC. A few minutes later I moved over to my laptop and tried to open an email that had been sent to that address. I received the error message "Decryption error: Decryption of this message's encryption content failed." for that message.

Unfortunately, I didn't screenshot this when it happened, but I was able to find [a representative image that shows the same error in the existing issues](https://user-images.githubusercontent.com/7829481/55908290-4f6bb380-5bd9-11e9-96d0-c14d323002bd.png).

Realizing that ElectronMail had been open on my laptop overnight I figured that the key generated for that address hadn't been synced down from ProtonMail, so I closed and reopened ElectronMail. This resolved the problem.

In terms of resolution, I'd consider checking ProtonMail for new account keys when decryption fails locally before raising the exception to the user. Failing that, forcing a restart when a new email address is detected or even just surfacing to the user that restarting the client may resolve some decryption issues would likely be helpful.

**Comment by vladimiry** [comment]
Thanks for the detailed issue description.

The case of `email.body` decryption error was handled to a sufficient extent with [v3.2.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.2.0) release (also see #129). It's handled in the way that any cause of body decryption failure won't break the local database syncing iteration but will skip the specific email body decryption with an option to `redownload the body` later (see the respective "redownload" gray button in the screenshot placed in [v3.2.0](https://github.com/vladimiry/ElectronMail/releases/tag/v3.2.0)). That button is similar to the "try again" link you see in [WebClient](https://github.com/ProtonMail/WebClient/)'s interface (also on your screenshot) but for the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) mode.

I believe that fixing the issue even further, like `checking ProtonMail for new account keys`, is up to enhancing the official web client, so that would be outside of the ElectronMail scope.
