### ISSUE TITLE
Keyboard shortcut for showing / hiding sidebar or getting preferences?

### ISSUE THREAD

**Issue by ylluminate** [vladimiry/ElectronMail#235]
I was fiddling around with ElectronMail and apparently stupidly turned off the menubar item and the sidebar. Now I cannot figure out a way to get into the settings or to toggle the sidebar back to on... Is there a way to fix this?  Can I edit the .plist config or some config file on macOS to get it back?

**Comment by vladimiry** [comment]
Few options:
- Open "Options" through the tray menu, Then navigate to "General" settings block and disable the"Hide controls bar (F12)" toggle. "Options" tray menu item was intentionally added for this specific purpose - you got the toolbar hidden and don't remember the hotkey, so you go to settings and get it back.
- Use F12 hotkey.
- Another option is to change the `hideControls` value in `config.json` file located in [settings folder](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg).

I will keep the issue open as clearly there is a need to rework the feature since a similar issue was opened before. Maybe I will turn that toggle into "Enabled F12 toolbar hiding hotkey", so:
- Users will have to explicitly enable the hotkey.
- Then only F12 hotkey will toggle the toolbar visibility. Right now both toggle in setting modal and F12 toggle it and F12 hotkey is always active.

**Comment by vladimiry** [comment]
Related issues:
- #128 
- #208

**Comment by vladimiry** [comment]
> I will keep the issue open as clearly there is a need to rework the feature since a similar issue was opened before.

I ended up introducing a new toggle for enabling F12 hotkey:
![f12](https://user-images.githubusercontent.com/1560781/73049273-12815c80-3e8d-11ea-990b-d50f0d1517a7.png)

**Comment by ylluminate** [comment]
F12 is not always enabled directly. I have, for example, F12 and fn-F12 both set for different volume controls on macOS since that is the default volume key w/o fn enabled.

**Comment by vladimiry** [comment]
In new version F12 is disabled by default. This should reduce a chance similar issues happened to users.
