### ISSUE TITLE
Foreign language support dropped?

### ISSUE THREAD

**Issue by dosenfleisch** [vladimiry/ElectronMail#260]
With Proton Version 4.0.0-Beta 9, coincidentally with the introduction of ElectronMail 4.3.0  the foreign language function within the protonmail gui has lost options and Englisch is now the default.

**Comment by vladimiry** [comment]
No explicit drop happened at the app side. Protonmail dev team probably changed some language related things in Proton Web UI after 4.0.0-beta8 and so we got feature lost in the app v4.3.0 since it comes with 4.0.0-beta9 Proton Web UI. So there will be a need to look into the how to get the feature back, likely a matter of adjusting the Proton Web UI build process.

**Comment by dosenfleisch** [comment]
Thanks for the prompt reply.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vladimiry** [comment]
Proton [recently switched](https://github.com/ProtonMail/proton-pack/commit/5e4c3f7a21665b8059ae96a0b6b2f84f608f8e1e) to loading the translations/locales from separate project which they don't seem share in https://github.com/ProtonMail/ yet.

**Comment by vladimiry** [comment]
There is some progress but no complete solution yet. See details in https://github.com/ProtonMail/WebClient/issues/176#issuecomment-594840300 if interested.

**Comment by vladimiry** [comment]
@dosenfleisch can you try [this](https://mega.nz/#F!x9YRFKbK!nDR4a7_oAXgegVpiRmG1SA) build? I tried switching the language in the account settings and it worked for me.

**Comment by vladimiry** [comment]
Fixed in https://github.com/vladimiry/ElectronMail/releases/tag/v4.4.1.
