### ISSUE TITLE
New version banner cosmetic bug

### ISSUE THREAD

**Issue by fm** [vladimiry/ElectronMail#264]
I was using v4.2.2, and had not opened it for a while. When I opened it, it showed me there was a new version available and mentioned _both_ 4.3.0 and 4.4.0. It should only display the latest version, not all I've missed. 

<img width="1282" alt="Screen Shot 2020-02-27 at 6 59 13 PM" src="https://user-images.githubusercontent.com/3654256/75500519-2ee84b80-599b-11ea-9a61-0f4f8c5a70c8.png">

**Comment by vladimiry** [comment]
There is no bug here. This is by design.

**Comment by fm** [comment]
Thanks for your answer. What's the reasoning behind displaying all the versions one is behind on?

**Comment by vladimiry** [comment]
The app displays links to all the missed releases, so the user could review the changelogs and make a decision about which version to use. For example, some Linux users might want to stick to the v4.2.2 since newer app versions are based on @electron version 8 and so there is no tray icon for some Linux users due to the lack of [Status Notifier Item standard](https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem/) support by the system.
