### ISSUE TITLE
[Feature request] Detect store updates availability

### ISSUE THREAD

**Issue by KaKi87** [vladimiry/ElectronMail#266]
Hello,

I would like to suggest for Electron Mail to detect updates availability from the store it has been installed from, and from GitHub only when the app hasn't actually been installed from a store.

The issue this feature would fix is that when being notified for a new update, the user, after failing to install it, will dismiss the notification, forget about it, thus never install it.

Thanks

**Comment by vladimiry** [comment]
Thanks for the suggestion. I understand the motivation but at this time will close the issue with won't fix status. My time/effort capacity is limited and so in order to keep maintaining the project, I have strike a balance between growing code-complexity/maintainability/functionality.

By the way, notifications about new releases published on GitHub by default disabled for Snap users. So if you explicitly enabled the option you probably did it for a reason.
