### ISSUE TITLE
Include account name in notification

### ISSUE THREAD

**Issue by ThHareau** [vladimiry/ElectronMail#280]
Hello, 

Would it be possible to include the account name in the notification? 

![image](https://user-images.githubusercontent.com/9265111/79197563-3fad2d80-7e32-11ea-8133-21f5f6763a7d.png)

The index of the account is not really helpful.

I think that the main email attached to the account would be more useful (something like: `email@domain.tld: 24 new emails`).

**Comment by vladimiry** [comment]
Initially, the login name was displayed in the notification message but then got turned to the index due to the privacy matters. We didn't have the aliasing feature at that time but we got aliasing supported since [v4.0.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.0.0) and so I think it's ok to render the alias in the notification message. If no alias defined then it would still be the index. Any thoughts on the described scenario?

**Comment by ThHareau** [comment]
For me at least, alias is perfect.

**Comment by vladimiry** [comment]
Alias displaying in desktop notification message is going to be enabled in the next release, https://github.com/vladimiry/ElectronMail/commit/04fc6592ea92d4bea2403a1caa49e7cfef15e1af.

**Comment by ThHareau** [comment]
That's awesome @vladimiry , I didn't expected it to be implemented that fast!
Thanks a lot

**Comment by vladimiry** [comment]
That was very easy change since we already had all the data in the store.

**Comment by vladimiry** [comment]
You can find in [this](https://github.com/vladimiry/ElectronMail/issues/282#issuecomment-618466438) message a link to the most actual work-in-progress build with 04fc659 change included.

**Comment by pangratt12345** [comment]
hey, sorry for digging up old topic, just for you information, there is a solution for including account name, alias, subject, sender's name, e-mail and timestamp in the notifications, as written in this issue https://github.com/vladimiry/ElectronMail/issues/387#issuecomment-3189435833
