### ISSUE TITLE
rpm on opensuse

### ISSUE THREAD

**Issue by gefagan** [vladimiry/ElectronMail#286]
Installing rpm on opensuse tumbleweed using yast software module (front-end for package manager zypper) throws missing dependency error for libappindicator, though in fact packages libappindicator1 and libappindicator3-1 are present in the standard repo. With the latter installed, I instructed zypper to "break" electronmail by ignoring missing dependencies, and it seems to work fine.

**Comment by vladimiry** [comment]
The latest released version v4.4.2 has following dependencies defined for the rpm package:
```
# default Electron dependencies
- libXScrnSaver
- libappindicator
- libnotify
# keytar dependencies
- libsecret
```

But not yet released v4.5.0 doesn't explicitly list the extra rpm dependencies. So are you using v4.4.2 release or v4.5.0 from master branch?

**Comment by vladimiry** [comment]
If you were using v4.4.2, can you try the work-in-progress v4.5.0 build the download link to which posted in [this](https://github.com/vladimiry/ElectronMail/issues/282#issuecomment-618466438) message? This build should not have the `libappindicator` library listed as a dependency.

**Comment by gefagan** [comment]
Looks like I'm on 4.4.2 - I'll try 4.5 and get back to you shortly.

**Comment by gefagan** [comment]
vladimiry, first let me say thanks for maintaining package-manager-friendly versions and not just appimages. 

Second, the rpm you linked to still hiccups on libXtst (I have libXtst6 version 1.2.3) and if it got past that it would complain about libXScrnSaver, which I don't seem to have at all, not even if I install XScreenSaver from standard repo. 

However, once again, it seems to work fine if I install it in spite of the warning. -GEF

**Comment by vladimiry** [comment]
[This is the place](https://github.com/develar/app-builder/blob/921a8e0ec3c2515e669174a6895704c77c55b41f/pkg/package-format/fpm/fpm.go#L137-L144) where the default rpm dependencies get defined. The list can be redefined at the project level, but only entirely (no extending or dropping some libraries). So this is an upstream/`electron-builder`-related issue and I'd really prefer the dependencies list to be maintained there since I believe they keep there the dependencies list that work for majority of rpm-package users.

By the way, I can locate the https://software.opensuse.org/package/libXtst and https://software.opensuse.org/package/libXScrnSaver in opensuse repository.

**Comment by vladimiry** [comment]
I still don't see what exactly needs to be done on the app side to handle the reported opensuse tumbleweed related issue, so closing for now. In general if that's dependencies related issue I'd ask to open it in https://github.com/develar/app-builder/issues first so all the electron-builder users could gain the benefit.
