### ISSUE TITLE
Unhandled error while startup

### ISSUE THREAD

**Issue by myangelaku** [vladimiry/ElectronMail#291]
It's my first time starting up ElectronMail after a really long time and a new update and I get this message, I think it's an error on my side, however, I tried reinstalling it and I got the same issue.
I can't seem to find a logfile right now, if there is one, I can put it here.
![ElectronMail_o59xdVfg8N](https://user-images.githubusercontent.com/28674643/81469206-12129480-91e4-11ea-9b5e-ef7cb391a00c.png)

**Comment by vladimiry** [comment]
This could happen if at least one of the data/config files listed in [readme](https://github.com/vladimiry/ElectronMail/blob/master/README.md#dataconfig-files-created-and-used-by-the-app) got corrupted for some reason. The app applies the atomic write scenario to prevent data files corruption but it might be that I missed something and so atomic write didn't handle all the cases.

So if you are going to use the app, to fix the issue I can advise to remove/rename the files in the following order and re-starting the app after each removal since `settings.bin` is the most important data file (files purpose by the above-shared readme link): `config.json`, `session.bin`, `database-session.bin`, `database.bin`, `settings.bin`.

**But let's see the log file first.** You can locate the `log.log` file in the [app settings](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) folder. You can either attach the log file here or send it privately to the email specified in https://github.com/vladimiry/ElectronMail/blob/master/package.json (`author` field).

**Comment by myangelaku** [comment]
Privet and Spasibo for the quick answer,

I did a full reinstall of ElectronMail by now and I'm still getting the same error. I did an index search on my PC and there don't seem to be any of the files you mentioned that might be associated with ElectronMail, as well as a log file.

Also, I can't start the application in the first place, so therefore I can't find any settings folder. However, this is how its folder looks like.

![Screenshot 1](https://myangel.aku.lu/qo9NfP.png)
![Screenshot 2](https://myangel.aku.lu/3vS2nT.png)

Once again, thank you very much.

**Comment by vladimiry** [comment]
You showed the app installation folder but I was writing about the app settings folder. The regular location of the app settings folder on Windows looks like `C:\Users\<user>\AppData\Roaming\electron-mail\`.

**Comment by vladimiry** [comment]
Also before install a new version I'd recommend to manually remove the folder you showed on the second screenshot as I guess it was created by a very old app version (not sure though as I don't have Windows system at hand to test the case).

**Comment by myangelaku** [comment]
> 
> 
> Also before installing a new version I'd recommend to manually remove the folder you showed on the second screenshot as I guess it was created by a very old app version (not sure though as I don't have Windows system at hand to test the case).

Actually, no, it wasn't, it was created by the new installation




> 
> 
> The regular location of the app settings folder on Windows looks like `C:\Users\<user>\AppData\Roaming\electron-mail\`.
Yeahhh, THAT was it. I had a look at all the files and some of them were extremely old. I also found a email-securely-app folder and after the deletion of all of the folders found there, the app started flawlessly.
Thank you very much!

![Screenshot](https://myangel.aku.lu/ktJXdN.png)

**Comment by vladimiry** [comment]
> Actually, no, it wasn't, it was created by the new installation

Ok, thanks for checking it on Windows and sharing the info with me.
