### ISSUE TITLE
Protonmail did a roll-back to beta 15.

### ISSUE THREAD

**Issue by arch-btw** [vladimiry/ElectronMail#300]
https://reddit.com/r/ProtonMail/comments/hanufi/rollback_from_beta16_to_beta15_no_longer_beta16/fv5o28m/

**Comment by vladimiry** [comment]
The app comes with static proton web client. So if you like you could keep using previous/v4.5.1 release which comes with 4.0.0-beta13 proton web client. I'm not reverting the proton web client version in the project but will update to the fixed client and publish new app release then since they say fix is coming soon.

**Comment by itisafrickinhighlander** [comment]
Webmail is back on Beta16.

**Comment by vladimiry** [comment]
Thanks for info, going to update the proton client later today.

**Comment by arch-btw** [comment]
Thank you @vladimiry

**Comment by vladimiry** [comment]
I just checked the https://github.com/ProtonMail and there is no published changes in comparison with what we already have packaged in v4.6.0. So right now it looks like no actions required from ElectronMail side.

**Comment by vladimiry** [comment]
It's now [confirmed](https://github.com/ProtonMail/WebClient/issues/129#issuecomment-646025207) that the originally deployed beta16 client code is fine. They re-deployed it after fixing the issue at the API/backend side. So released v4.6.0 app version is just fine.
