### ISSUE TITLE
Tor entry point fingerprintability

### ISSUE THREAD

**Issue by User486375** [vladimiry/ElectronMail#301]
How easily fingerptintable would someone using the tor entry point with ElectronMail be, compared to most people who use https://protonirockerxow.onion/ directly in the Tor Browser Bundle? 

At first, I thought having a different user agent would be the main issue, but thinking on the issue further isn't not loading the web client alone, fingerprintable? As even using the hidden service you're likely the only circuit which isn't trying to load the web client resources, though this would also affect non hidden service entry points even more so. I think defaulting to a spoofed tor browser user agent when connecting to the tor entry point would help a lot, but I don't know how to solve the latter issue besides loading the web clients resources (on each page?) in the background but never actually using them for the security benefits mentioned in #80.

Maybe I'm overthinking things and any input would be appreciated. Just seeing #273 being accepted got me thinking about this and how people using the tor entry point wouldn't really benefit from that change at all, considering everyone else's user agent would be the TBB. As well as the extremely small set of people who use ElectronMail with ProtonMail let alone the Hidden Service option.

**Comment by vladimiry** [comment]
Since proton web client is open source creature ElectronMail is not the only way to use a static web client. Anyone could build it for a local run. In general, I tend to think that those who use tor or tor browser would also prefer to run a static web client since spoofed resources could potentially affect the security/privacy to a greater extent than just infgerprinting. By the way, Bridge users also don't load the web resources.

So if this is a feature request for loading online web clients then this would be `won't fix`.

> loading the web client resources (on each page?) in the background but never actually using them for the security benefits mentioned in #80.

Even if we do this there would be a need to coordinate things initiated by the background/live/dummy page with the actual API requests we send later. For example, API requests include the used web client version (`x-pm-appversion` header) and so then if we don't explicitly pick this version from the background/live/dummy page and explicitly set it for use in API requests then a user might likely be detected as the unusual one due to some incoordination (unlikely they automatically track such incoordination cases but that should be technically possible). And this is just one example. Even if we detect all the things need to be coordinated it still won't work reliably:
- The process of detecting things to coordinate will need to happen after every web client code update. So a lot of dull work and if something is missed then work becomes pointless.
- Such detection won't make much sense since the app uses a static web client but background/live/dummy web client might already be updated many times with added more things that we don't yet coordinate.

**Comment by User486375** [comment]
>By the way, Bridge users also don't load the web resources.

Oh true, sorry I forget about that as it's only for paid users.

>So if this is a feature request for loading online web clients then this would be `won't fix`.

Well I more so thought it would be interesting to get feedback on and judging by the rest of your comments I'd say the only plausible way would be to actually just verify that a web client was loading the same resources and use the live client. But obviously that's not plausible unless ProtonMail developed their own desktop client just like Tutanota did.

Lastly you didn't seem to have any comments on the suggestion of spoofing the apps user agent for connections to the hidden service, would this not be a simple change with an obvious privacy benefit? Unless there's compatibility issues spoofing it.

**Comment by vladimiry** [comment]
> Lastly, you didn't seem to have any comments on the suggestion of spoofing the apps user agent for connections to the hidden service, would this not be a simple change with an obvious privacy benefit? Unless there's compatibility issues spoofing it.

Opt-in per-account feature of rotating user agent is already enabled since v4.5.0, see #273 for details.

**Comment by User486375** [comment]
>Opt-in per-account feature of rotating user agent is already enabled since v4.5.0, see #273 for details.

Yes I had mentioned #273 as to what inspired me to write this issue in the first place and how I thought it was useless for people using the hidden service. I still fail to see how that is beneficial to blending in your API calls to the hidden service with everyone else who uses it through TBB. Which is why I'm suggesting spoofing the TBB's user agent.

**Comment by vladimiry** [comment]
> Which is why I'm suggesting spoofing the TBB's user agent.

I don't really get what you mean by this. You can put any user agent strings to the array specified in `config.json` file.

**Comment by User486375** [comment]
Ah I didn't fully read your comment on that just the list of rotating user agents itself, my bad. 

Though as you mentioned compatibility issues, as electron is of course using chromium and not gecko. I still think having the default (or an option) of it being spoofed for every user connecting via the hidden service would be best if it doesn't run into compatibility issues when tested. As the whole point of #273 as far as I can tell was to address fingerprinting multiple accounts to tell that they're using ElectronMail? Which in my opinion is pretty useless if you're using the same IP so that disregards everything but tor exit nodes or the hidden service in my opinion, as VPNs won't have a significant enough anonymity set to not easily link the accounts. And like I said before considering basically only ElectronMail users will connect to with the hidden service serving chrome user agents, I think it's still useless in this case. If I'm missing the benefit of #273 do tell, though I think having it easily customizable is nice.

**Comment by vladimiry** [comment]
I'm not here to protect #273 feature but will put some points though.

> Though as you mentioned compatibility issues, as electron is of course using chromium and not gecko.

Compatibility issues possibility doesn't mean the issues will appear in reality. Most likely proton dev team doesn't rely on user agents as that's considered a very bad practice for a long time already. You could confirm this point by placing the issue in https://github.com/ProtonMail/WebClient/ if that's a concern.

> Which in my opinion is pretty useless if you're using the same IP

You are not forced to use the same IP for all the accounts added to the app. The app allows configuring the proxy per account. So you could run multiple Tor instances specifying different exit nodes ranges based by location. And it's not limited by Tor use only.

> And like I said before considering basically only ElectronMail users will connect to with the hidden service serving chrome user agents, I think it's still useless in this case.

There is a link to the #273 near to the `User-agent rotation` toggle. So anyone concerned could follow the link and realize that the user agents list is not hardcoded. After all, the `Extended Options` block on the account edit form is not for a regular user and that's why it's collapsed by default.

**Comment by User486375** [comment]
> You are not forced to use the same IP for all the accounts added to the app. The app allows configuring the proxy per account. So you could run multiple Tor instances specifying different exit nodes ranges based by location. And it's not limited by Tor use only.

Well I had thought about that and came to the conclusion that rotating it isn't useful in that scenario either. As if you're using different exit nodes then having different user agents is irrelevant. And as you're defending against ProtonMail becoming a malicious actor, it's going to be trivially easy to correlate exit node requests with the default chromium user agent of ElectronMail let alone a rotating one. As I think it's easy to assume, a very small subset of users use ElectronMail, an even smaller subset of that use it with tor exit or onion service and then an even smaller set of those users would rotate their user agent and lastly if you customize the rotating list that make you even more unique. 

So compromised ProtonMail observes account 1 requesting through tor rotating its user agent. It also sees account 2 doing the same with the same set of rotating user agents. No other users are currently logged in through those listed user agents, making correlation trivial. While if it was a TBB fingerprint they would have to go to extreme efforts to correlate circuits not serving the web client with individual accounts.

**Comment by vladimiry** [comment]
> easy to correlate exit node requests with the default chromium user agent of ElectronMail let alone a rotating one

You are not forced to put the default user agents to the user agent list.

> you're defending against ProtonMail becoming a malicious actor

Not really. But if something is technically possible it might happen one day.

> So compromised ProtonMail observes account 1 requesting through tor rotating its user agent. It also sees account 2 doing the same with the same set of rotating user agents

The user agents list is exhausting. Account 1 acquires a random user-agent value form the list and then that user agent value is no longer in the list. So account 2 won't have the same user agent as account 1 unless you put duplicated values in the list or the list size is smaller than the number of accounts added to the app with enable rotating option (when the list gets empty then it gets reset to the default/full list).

I'm closing the issue since no code changes expected to happen within this issue and due to the fact that the discussion doesn't go anywhere since I see no arguments on how to make something work better but more like steering the conversation towards protecting implemented opt-in feature to be useful. The #273 feature is disabled by default, so if you see no point in using it you could pretend it doesn't exist. If you like keeping #237 related discussions consider doing that in #297
