### ISSUE TITLE
[feature request] Abillity to skip master password

### ISSUE THREAD

**Issue by Gieted** [vladimiry/ElectronMail#309]
First thing what you see after installation of ElectronMail is a prompt to set a master password. Why you even need one? 
Why not just store the secrets in OS services (or add an option to)? 
What you mean by saying "Saving the master password on computer weakens the security."? Most desktop programs actually don't log you out after a restart (including privacy/security ones, like signal-desktop) and don't require any additional password, so why ElectronMail shows a red warning, such as it could lead to a security disaster?
Does saving the master password actually increase my security, when I'm using full disk encryption (BitLocker)?

**Comment by vladimiry** [comment]
Master password skipping request gets rejected since all the sensitive app settings and data if the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option enabled need to be stored encrypted (see the `Data/config files created and used by the app` section in [readme](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app)).

Master password saving option is added for those who prefer the convenience of storing the master password in the system's keychain which makes the fully automated login into the app and email accounts possible (done using [keytar](https://github.com/atom/node-keytar) native module).

I'd recommend exploring the app capabilities on your own since I believe then many of your questions will be taken off the agenda. You might also want to explore the [persistent session](https://github.com/vladimiry/ElectronMail/issues/227) feature.

**Comment by vladimiry** [comment]
> My proposal is to encrypt user's data with a random key **by default** and add setting a master password as an option in settings.
Many programs are doing so, e.g. Firefox.

This would make the app less secure by default since currently the master password/key by default is not saved anywhere and enabling saving behavior requires the option to be explicitly activated by the user. I understand why Firefox and alike programs follow the way you described but for this project I prefer it to act like it's done now.

Besides that, there are scenarios when the app won't be able to save anything in the system's keychain since there is no keychain provider installed on the system. See https://github.com/vladimiry/ElectronMail/issues/57#issuecomment-569286627 for details if interested.

> ElectronMail should follow this convention in order to be more friendly to non-technical users

I'm going to make the master password setup form more informative to let non-technical users become more technical.

![strip 2](https://user-images.githubusercontent.com/1560781/89110016-0afbcb00-d44f-11ea-8602-dbfa449be53f.png)

**Comment by vladimiry** [comment]
Warning message shown on screenshot in previous message gets changed to:

> Activating <code>"Keep me signed in"</code> option enables saving the master password in the system's keychain of your computer. In general, storing the password weakens the security but enables automatic login to the app so you don't have to manually enter the master password each time you start the app.

**Comment by vladimiry** [comment]
Pushed to master warning message:
```
Activating <code>"Keep me signed in"</code> option enables saving the master password in the system's keychain. In general, storing the password on computer weakens the security but enables automatic login to the app so you don't have to manually enter the master password each time you start the app.
```
