### ISSUE TITLE
The flatpak of ElectronMail sometimes doesn't load protonmail at all, whereas the snap version works always

### ISSUE THREAD

**Issue by pizzadude** [vladimiry/ElectronMail#311]
This is on Fedora 32 KDE. I tested the Flatpak version vs the Snap version.

The snap version works always. It 100% of the time loads protonmail.

The flatpak version of ElectronMail about 50% of the time doesn't load protonmail unless I restart the application. It's trial and error until it loads.

Any ideas what could cause this issue with the flatpak version? I don't have these issues with any other electron applications packaged as flatpak.

This seems like a race condition of some sort.

**Comment by vladimiry** [comment]
Can't say something specific at the moment since I couldn't yet reproduce the issue. Have tried starting the app more than 10 times having first 1, then 3 accounts added to the app. The @ProtonMail's web client gets well loaded every time so far.

Maybe try enabling small account loading delay, like 2-4 seconds range. To do that locate the extended options collapsible block on the account edit form, see the screenshot here https://github.com/vladimiry/ElectronMail/releases/tag/v3.1.0.

Another blind guess is the following. Maybe try removing all the folders in $HOME/.var/app/com.github.vladimiry.ElectronMail/config/electron-mail/ before starting the app. Those folders a system like, produced and maintained by @electron itself (the app only possesses the files listed [here](https://github.com/vladimiry/ElectronMail#dataconfig-files-created-and-used-by-the-app)). If it helps, we could tweak the app bootstrapping/starting flatpak script to remove those folders before every start.

**Comment by vladimiry** [comment]
Closing the issue as inactive.

**Comment by mike2307** [comment]
Please reopen this issue.
For me this happens not just 50% of the time but rather most of the time.

After entering the master password I obviously run into some timeout and get:

> Failed to load "webclient1://mail.protonmail.com/blank.html?loader-id=d66d46e4-1288-4095-9f3a-d55c653d3158" page in 15000ms

After that I have to quit electronmail entirely, start it again and give it another try...

**Comment by pizzadude** [comment]
I just gave up and used the snap version for now.

**Comment by vladimiry** [comment]
The issue got closed as inactive. This means there was no constructive reaction to the response I posted and it's still like that. There were two things named for you to try.

**Comment by pizzadude** [comment]
I forgot about the issue. I tried both suggestions. They didn't have any effect.

**Comment by vladimiry** [comment]
Then I have no more workaround guesses at this time. The code packed into the flatpak package is the same as for the rest of the Linux packages so there is something flatpak container handles/does differently than a regular Linux system or pacman/appimage containers which demonstrate no issue. The issue is still unreproducible on my side so the ideas of how to narrow down the scope and make the issue reproducible are welcomed.

**Comment by pizzadude** [comment]
I understand. I think it's worthwhile to have this issue stay open in case some other people run into this issue so they know it's not just them.

**Comment by mike2307** [comment]
I attached the log file of a failed start (with silly logging enabled).
[log.log](https://github.com/vladimiry/ElectronMail/files/5101143/log.log)

For me also your 2 suggestions didn't work.

**Comment by vladimiry** [comment]
I'm going to enable earlier page loading detection initialization and also extend logging so maybe next flatpak release will be demonstrating better stability.

**Comment by vladimiry** [comment]
I've made some improvements based on guesses so can someone test this beta build `flatpak install --user https://dl.flathub.org/build-repo/24615/com.github.vladimiry.ElectronMail.flatpakref`? See details [here](https://github.com/vladimiry-playground/electron-mail-ftatpak/releases/tag/v4.8.1-b09de1b). Before running the app please set `logLevel` value to `verbose` in `config.json` file.

**Comment by mike2307** [comment]
Unfortunately I didn't notice any change.
Log attached. 
[log.log](https://github.com/vladimiry/ElectronMail/files/5103711/log.log)

**Comment by vladimiry** [comment]
Another build to test `flatpak install --user https://dl.flathub.org/build-repo/24630/com.github.vladimiry.ElectronMail.flatpakref`. There is no logic change but even further extended logging.

**Comment by mike2307** [comment]
Log from the latest version:
[log.log](https://github.com/vladimiry/ElectronMail/files/5104960/log.log)

**Comment by vladimiry** [comment]
Thanks for the logs. The key/page-loading log lines located between `did-start-loading` and `did-stop-loading` lines. When it works there is a bunch of performed actions but when it doesn't get loaded the `did-stop-loading` goes right after `did-start-loading` with no actions in between. Extending the logging I subscribed to all error-like events I've located and was hoping there will be some kind of cause logged but it's empty so it's still unclear why the page doesn't get loaded.

**Comment by mike2307** [comment]
For me this started to magically work again some weeks ago. Don't know what it was originally caused by but I haven't experienced any issues for some time now...
Is this also the case for someone else?

**Comment by vladimiry** [comment]
There is no magic when it comes to computer-related stuff. So apparently the issue has got resolved upstream at some level. You know, these days most of the complex programs depend on a lot of things installed on your system.

**Comment by pizzadude** [comment]
Confirmed fixed.
