### ISSUE TITLE
Update of database not working

### ISSUE THREAD

**Issue by uberneko** [vladimiry/ElectronMail#314]
Hello -
I was at v4.6.0 - everything was working fine, one month ago. I didn't use it during one month.
I just downloaded the Appimage of v4.8.0, but then the database (switching to offline mode) would not update.
Not sure if it is normal..
(using Appimage on a ubuntu 20.04 based OS)

**Comment by vladimiry** [comment]
If the network connection is online and you signed-in into the account having the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) option enabled then the local database is supposed to be updating reactively. If updating is not happening then it's not normal but the provided information is not enough for me to help you investigate the case.

The simplest option would be in doing a cold local database refresh. Means removing the `database.bin` and `database-session.bin` files from the settings folder and restarting the app (you might want to backup those files first). Again, you signed-in into the account for the syncing process to start.

**Comment by uberneko** [comment]
Thanks for that quick answer ! Yes network connection is fine, I signed-in with local store option enabled. I'd gladly provide you additional info but I don't know what to give -
Strangely the database.bin file is dated today, so it has been saved by the app, but without changes.
I updated regularly since... I even don't remember, 1-2 years ago ! And each time the new Appimage was updating the database as expected.

I gonna try that refresh, but I have 370Mo of emails so it will take time... and indeed I will back up it.
Thanks !

**Comment by vladimiry** [comment]
> I gonna try that refresh, but I have 370Mo of emails so it will take time... and indeed I will back up it.

This is not so big figure anymore :smile:  see https://github.com/vladimiry/ElectronMail/issues/313

> I have a ProtonMail mailbox with ~33000 items, totalling about 1.9GB in my local database.

**Comment by uberneko** [comment]
Ok - database re-loaded.
I'll take care next update to check if it updates it correctly -
Thank you !

**Comment by uberneko** [comment]
(Note : for the same amount of emails - I noticed that the database.bin file has been reduced by a third...)

**Comment by vladimiry** [comment]
> (Note : for the same amount of emails - I noticed that the database.bin file has been reduced to a third...)

The wild guess is that protonmail is not streaming the scheduled/automatic mails removing from bin events to the events queue and so the app simply doesn't see that the old mails got automatically removed from the bin. I remember that Tutanota email provider had such issue. I'm not sure though that protonmail at all has the feature of automatic removing the emails being located in the bin 30 days.

**Comment by vladimiry** [comment]
No code changes expected to happen at this time so closing the issue.

**Comment by vladimiry** [comment]
I've just found out in https://github.com/ProtonMail/proton-mail/issues/53 that the app is missing to process the `Refresh: 255` value returned by `/api/v4/events/<EventID>` @protonmail API. This means that if the app was not used for like 21+ days (sync process was not triggered) then it's highly likely that a user will face the data loss issue since `Refresh: 255` means that all the previously downloaded/cache data should be dropped and downloaded from scratch. So I originally thought that `/api/v4/events/<EventID>` keeps the entire history and so allows to reconstruct the state regardless from passed `EventID` value but in reality, it's not like that.

@uberneko, this is likely a reason you were facing the missed data issue. So reopening as a bug.

**Comment by vladimiry** [comment]
Since the v4.9.3 users who have the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) feature enabled for at least one email account will be prompted to refresh the local database (full/bootstrap fetch):

![dialog2](https://user-images.githubusercontent.com/1560781/101494681-b2968600-3978-11eb-9db8-1064d05f540e.png)
