### ISSUE TITLE
Update notes don't load for me

### ISSUE THREAD

**Issue by samuelroland** [vladimiry/ElectronMail#323]
When i click here:
![image](https://user-images.githubusercontent.com/47849646/92406601-b7109000-f138-11ea-8080-a7a652c876ef.png)
This popup appear but doesn't work well:
![image](https://user-images.githubusercontent.com/47849646/92406474-69942300-f138-11ea-8586-e567091d7bce.png)
The update notes don't load for me. Am i alone with this problem ? The app doesn't work then (i can't click on the buttons). I need to kill the app process in the task management and restart the app to remove this popup.
Any ideas ?

**Comment by vladimiry** [comment]
This is a known issue. A minor thing and so I used to postpone it. Apparently I need to adjust the https://github.com/ProtonMail/ projects build workflow located in https://github.com/vladimiry/ElectronMail/tree/master/scripts/prepare-webclient.

**Comment by vladimiry** [comment]
The issue has been resolved in 12c6982 like a week ago and the change will be included in the next release.

By the way, that changelog you get displayed in modal a simply the https://github.com/ProtonMail/WebClient/blob/v4/CHANGELOG.md file transformed to the HTML format. So you won't see the detailed/actual beta version related information there since @ProtonMail doesn't put the respective changes to the file.

**Comment by vladimiry** [comment]
WIP build is placed [here](https://mega.nz/folder/g0JHxaSR#Hyih6CMm5Jzp8I9gEwp4qQ).
