### ISSUE TITLE
Is ProtonCalendar Desktop notifications working?

### ISSUE THREAD

**Issue by SchrodingerZhu** [vladimiry/ElectronMail#328]
I get no popup on KDE plasma.

**Comment by vladimiry** [comment]
The cfa3b00 change should make the [Notification](https://developer.mozilla.org/en-US/docs/Web/API/notification) triggered by @ProtonMail on calendar page work. The change is going to land in the next release.

But it's not really helpful since:
- v4-beta designed by @ProtonMail in the way so you have to keep the Calendar page open to get the desktop notifications/alarms.
- When you click the button no notification nothing will happen since the app currently doesn't implement the thigh integration with the Calendar page. Such integration is supposed to happen in #229. Besides I believe it's technically possible to make the desktop notification work regardless of the page being opened so you get the alarm displayed even if you have the WebClient/Mails page opened.

**Comment by vladimiry** [comment]
The work-in-progress v4.9.0 version with the included fix is uploaded [here](https://mega.nz/folder/YpIigT7R#eGH5QExiGLi1lHstiFallQ). For everyone running this build I highly recommend enabling the opt-in `Block non "API entry point"-based network requests` option for all accounts (see how to enable it on the screenshot in https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619)

**Comment by IberratioActus** [comment]
> 
> 
> The work-in-progress v4.9.0 version with the included fix is uploaded [here](https://mega.nz/folder/YpIigT7R#eGH5QExiGLi1lHstiFallQ). For everyone running this build I highly recommend enabling the opt-in `Block non "API entry point"-based network requests` option for all accounts (see how to enable it on the screenshot in [#312 (comment)](https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619))

I did update and still can't get desktop notifications from the calendar

**Comment by vladimiry** [comment]
- Does it work in browser?
- What are the issue reproducible steps? I just have created the event and got the notification displayed (having Calendar page opened, not the Mails page).

**Comment by IberratioActus** [comment]
> 
> 
>     * Does it work in browser?
> 
>     * What are the issue reproducing steps?
> 
> 
> I just have created the event and got the notification displayed (having Calendar page opened, not the Mails page). Also clicked the "Send test notification" button in Calendar Settings section and it worked too.

It does work in the browser version, yes. 

So the notification option in the ElectronMail app was "enabled" from the beginning iirc. Clicking "send test notification" doesn't do anything, neither does creating an event for like ~5min in the future. The timer for sotifications within the event-settings is set to "1min before"

**Comment by vladimiry** [comment]
What is the commit/hash value you see in the app about window (near to version number)?

**Comment by IberratioActus** [comment]
> 
> 
> What is the commit/hash value you see in the app about window (near to version number)?

ElectronMail v4.9.0 f0308181

**Comment by vladimiry** [comment]
It's f030818 value, thanks. It worked for me for the same build, so the issue appears to be system-dependent and at the moment I have no guess what I could do to make it work for you. But I'm considering enabling Calendar desktop notifications/alarms regardless of the opened page (see https://github.com/vladimiry/ElectronMail/issues/229#issuecomment-695130931 for details) and maybe then it will work for you since that will be a custom notification triggered not by proton but by app.

**Comment by IberratioActus** [comment]
So, found out what the issue was after noticing that also the regular windows calendar doesn't give me any notifications. And of course it's a really dumb reason why.

There's this "do not disturb" function in Win10 that I apparently had activated without knowing. It doesn't show in the windows-notifications-settings, that's why I didn't see it at first

**Comment by vladimiry** [comment]
Thanks for the update. So if I get it right the shared before f030818 build is functional for you.

**Comment by IberratioActus** [comment]
Well it's f0308181 now, but yes, it's working :) ty
