### ISSUE TITLE
Unhandled Promise Rejection config.json updated by another process

### ISSUE THREAD

**Issue by xingped** [vladimiry/ElectronMail#330]
Unhandled promise rejection error below. I wasn't doing anything, it was just sitting in the background and I wasn't updating that file.

OS: Windows 10
Version: 4.8.0

```
Unhandled Promise Rejection
Error: "C:/Users/<user>/AppData/Roaming/electron-mail/config.json" has been updated by another process. Revisions of the persisted (22) and payload (21) data don't match
    at Store.<anonymous> (C:/Program Files/ElectronMail/resources/app.asar/node_modules/fs-json-store/lib/private/store.js:273:35)
    at step (C:/Program Files/ElectronMail/resources/app.asar/node_modules/fs-json-store/node_modules/tslib/tslib.js:141:27)
    at Object.next (C:/Program Files/ElectronMail/resources/app.asar/node_modules/fs-json-store/node_modules/tslib/tslib.js:122:57)
    at fulfilled (C:/Program Files/ElectronMail/resources/app.asar/node_modules/fs-json-store/node_modules/tslib/tslib.js:112:62)
```

**Comment by vladimiry** [comment]
The app by design, initially, and intentionally writes settings and config files having enabled the optimistic locking scenario (versioning). It's done this way to prevent undesirable data overwriting and simplify detecting the timing/racing issues which could take place when the code logic is heavily asynchronous.

Normally when you explicitly modify the settings/configs via the UI the app blocks the form/UI until the already executed action gets finished. The error you posted, generally, indicates that some pieces of actions performing coordination are still missing in the app code.

> I wasn't doing anything, it was just sitting in the background and I wasn't updating that file.

I've looked into all the code places of writing the config file and since you didn't explicitly interact with the UI I guess the most probable problematic config write case is the window state saving (size, position, maximize state, etc).

f4e3672 change should to prevent the issue to happen again.
