### ISSUE TITLE
[Bug] Stuck on hyperlink modal

### ISSUE THREAD

**Issue by KaKi87** [vladimiry/ElectronMail#334]
Hello,

When writing an email, once the hyperlink modal is opened, I can't close it, whether I validate or cancel.

Thanks

**Comment by vladimiry** [comment]
Can you verify if [this](https://mega.nz/folder/NooClQjS#SwuwWXAaD0AHoMQQ-I9L8A) build affected? It's a work-in-progress build assembled as a result of #332 work.

**Comment by vladimiry** [comment]
- The actual app code doesn't use https://github.com/ProtonMail/WebClient/ project anymore but https://github.com/ProtonMail/proton-mail.
- There is no confirmation that https://github.com/ProtonMail/proton-mail demonstrates the placed issue.
- A new app version with #332 change included is going to be released soon. Probably this week.

**Comment by tianalemesle** [comment]
Hello,
Mega.nz is not working for me, could you try a website that supports direct download ?
Thanks

**Comment by KaKi87** [comment]
Hello,
Mega.nz is not working for me, could you try a website that supports direct download ?
Thanks

**Comment by vladimiry** [comment]
> website that supports direct download ?

No such option at the moment.

**Comment by KaKi87** [comment]
[anonfile.com](https://anonfile.com), [file.io](https://file.io), etc.

**Comment by vladimiry** [comment]
Package type (linux/macos/win)?

**Comment by KaKi87** [comment]
AppImage please.

**Comment by vladimiry** [comment]
https://anonfiles.com/Bav1F9f0p4/electron-mail-2020-10-13-v4.9.0-b3aac8a_tar

**Comment by KaKi87** [comment]
The bug is fixed in this build, thanks.

**Comment by vladimiry** [comment]
Just for you to know. In the build I shared the remote retests to the URL origins other than selected in the "API entry point" dropdown value are blocked by default. So for example you won't be able to load inlined in the email message images. In the released version this is going to be an opt-in feature (disabled by default).

**Comment by vladimiry** [comment]
> https://anonfiles.com/Bav1F9f0p4/electron-mail-2020-10-13-v4.9.0-b3aac8a_tar

I don't recommend using this build on daily basis but only testing the original issue case since I have a reason to believe that this version comes with proton web client that has a leading to the privacy-compromising flaw (the issue has been reported). For the same reason, I would not yet use the https://beta.protonmail.com in the browser.

**Comment by KaKi87** [comment]
I see, could you please link me that issue ?

**Comment by vladimiry** [comment]
> link me that issue ?

The issues of this type are not supposed to be publicly disclosed until they get fixed. I'm going to place update message in #332 when I get new information.

**Comment by tianalemesle** [comment]
So, I'm back on v4.8.0, and I can no longer reproduce the bug ? Is it possible that it is still using the same website as in v4.9.0 ?

**Comment by vladimiry** [comment]
> Is it possible that it is still using the same website as in v4.9.0 ?

Unlikely since the proton's web client packaged in the app is a static asset. But technically it's possible for proton client to load the JS stuff from a remote server and then embed it to the page (I don't think they do that). In not yet released v4.9.0 the `Blocking all non "API entry point"-based network requests` feature is enabled in order to detect/block shady network requests, see https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619 for details. By the way, enabling that option suppresses the issue I mentioned in the previous message.

**Comment by vladimiry** [comment]
The most recent v4.9.0 build uploaded [here](https://mega.nz/folder/QtwCQIZZ#sfAOA3Tobhj2n7QjuWLgUw). The named before issue gets suppressed by enabling `Block non "API entry point"-based network requests` option (respective screenshot posted in https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619).
