### ISSUE TITLE
Cannot launch electronmail

### ISSUE THREAD

**Issue by Souravgoswami** [vladimiry/ElectronMail#352]
I am using Arch Linux, and I got electronmail 4.9.2.

With the newest Electron9 v9.3.5, I can't seem to launch it. Although it worked with the old version v9.3.3.

I am getting this error:

```
Unhandled Promise Rejection
Error: ERR_FAILED (-2) loading 'file:///opt/ElectronMail/resources/app/app/web/browser-window/index.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1493)
    at Object.stopLoadingListener (electron/js2c/browser_init.js:205:1868)
```

I also tried downgrading electron9 to 9.3.3 now, but it's still not working...

**Comment by vladimiry** [comment]
Each app release comes with the specific @electron version and that's the only @electron version the app should be used with. You don't need to deal with @electron versions since the app comes with it built-in. The v4.9.2 by the way [comes with @electron 11.0.0-beta.20](https://github.com/vladimiry/ElectronMail/blob/v4.9.2/package.json#L220) so I don't clearly get what you mean by specifying version 9.

**Comment by Souravgoswami** [comment]
Oops that wasn't the problem either. Turns out I added a huge stack limit in my /etc/security/limits.conf:
```
sourav soft stack 2000000
```

And I did that on purpose, and forgot to remove that, and I was unable to launch chromium, edge, falkon, etc. as well. I later figured that out...
