### ISSUE TITLE
Is there anyway to enable dark mode on emails themesleves?

### ISSUE THREAD

**Issue by se7enge** [vladimiry/ElectronMail#384]
As stated in the title, I am just wondering if there is anyway to get my emails to appear as a dark background with white text. I have the native dark mode enabled and I really like the look, but it is quite annoying, for my eyes at least, to have the emails be white when everything else is darkened.

If not possible through the basic settings, then is there some way to do this via css? I am relatively unfamiliar with css so apologies if there is an obvious way to do this with a custom css profile.

Any help is much appreciated :)

Josh

**Comment by vladimiry** [comment]
> emails to appear as a dark background with white text

Official / @protonmail UI does have a dark theme but as far as I know email the body content is still being rendered as black text on white background. It's in general understandable since it's note easy to render random HTML code in proper dark mode.

As for the enabling a custom dark mode in the app, keep track of #242. So not implemented yet but in general possible including the email body content rendering since the app in [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) / `database view` mode renders the body content in text format only (HTML gets transformed to text). The initial / minimal change was highlighted and made in relation to #238 (so far only gray color took place instead of originally used white one).

> then is there some way to do this via css? I am relatively unfamiliar with css

In general it's possible. But you have to be well familiar with CSS in order to fulfill the task. Custom CSS support is enabled in the app since https://github.com/vladimiry/ElectronMail/releases/tag/v4.10.0, see #355.

**Comment by Jombazi** [comment]
Care to share the custom css code ?

**Comment by romeoacevedo** [comment]
Did you ever get the CSS code to change the email to dark mode?
