### ISSUE TITLE
On Windows, none of the newer releases beyond 4.10.2 work

### ISSUE THREAD

**Issue by camalolo** [vladimiry/ElectronMail#413]
Hello,

I tried all the versions after 4.10.2 on Windows 10

None of them work, upon launch the application quits immediately

How can I find the problem ? Is there a logfile I can check for errors ?

Thank you

**Comment by vladimiry** [comment]
The default log file location on Windows is `C:\Users\<user>\AppData\Roaming\electron-mail\log.log`. If the app starts, the app data folder gets open via [this](https://github.com/vladimiry/ElectronMail/blob/master/images/open-settings-folder.jpg) menu.

- Do you run the latest gen Ryzen/Intel CPU (at some point @electron faced the related issue which has been fixed in the recent @electron releases so the fix didn't come yet into the app release)? If you do try the v4.12.3 WIP build uploaded [here](https://mega.nz/folder/coxEVDRJ#Ym_15bI-Rxnh7dEbARf4Pg) (the build log is [here](https://github.com/vladimiry/ElectronMail/runs/2778590646?check_suite_focus=true)). This will likely fix the issue. I recommend to backup all the app data file before you start this/WIP build (all the files produced and modified by the app listed in the [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ), see point `#2`). This release modifies the app data files format, so you better do backup to be able to rollback the app version (noted in release notes).
- What is the database.bin and database-session.bin files size if any (located in the same folder as log file)?
- If you have got the above named files, what is the email messages count rounded to thousands you have got in the account?

**Comment by camalolo** [comment]
Dear Vladimir,

The WIP build works ! And yes I am running on a Ryzen 5 5600X, so it seems you have provided the solution.

If you still need the other information you mentioned let me know, as I imagine those are unrelated to the Ryzen support issue, I won't include those for now, but I will if you need me to.

Thank you very much for your service

**Comment by vladimiry** [comment]
> If you still need the other information you mentioned let me know

Nope. Sufficient information was provided before in #412 by @KevC117 (the build I posted link to in previous message was also originally provided in that issue). You might also want to thank @t57ser who reported the [upstream](https://github.com/electron/electron/issues/29335) issue.

New app release with the @electron update and so resolved issue is going to be published soon, possibly this week.

**Comment by camalolo** [comment]
Well thank you to all of you @KevC117, @t57ser and @vladimiry !
