### ISSUE TITLE
Memleaks

### ISSUE THREAD

**Issue by Nothing4You** [vladimiry/ElectronMail#424]
Hi,

I'm using 9 mailboxes currently with a total of less than 200 mails in all mailboxes combined (all folders).
In my case that's a total of ~6.5GB memory usage currently with 3 of the processes taking around 1.9GB each.

After restarting the application and activating each account once I'm at around 1GB memory.
I've updated all mailboxes to not use local storage and memory usage jumped to ~2GB temporarily while saving and dropped to the previous value of ~1GB just after.

I get roughly the same memory usage both with and without local storage (including after restart).
I don't think this is the same as #372 as I would then expect initial high usage.
I don't have numbers over time yet as I just noticed this today.

**Comment by Nothing4You** [comment]
This is on ElectronMail v4.12.4 btw.

**Comment by vladimiry** [comment]
The actual significant memory leak was resolved in the recent / https://github.com/vladimiry/ElectronMail/releases/tag/v4.12.4 release. Since the related fix, I was observing the memory usage for one account for 3 days and it was, in general, looking stable.

At the moment I have no reason to believe that the possible remaining leaks are caused by the app-related code but by the dependencies and/or loaded in the webviews stuff (like @protonmail web clients).

**Comment by vladimiry** [comment]
> I'm using 9 mailboxes currently with a total of less than 200 mails in all mailboxes combined (all folders).
In my case that's a total of ~6.5GB memory usage currently with 3 of the processes taking around 1.9GB each.

If you calculated and listed things correctly, then given just 200 mails in all mailboxes, having 3 processes with 1.9GB memory consumption looks like a potential issue.

**Comment by Nothing4You** [comment]
doesn't seem to be reliably reproducible, currently 10d+ process uptime and relatively stable at about 512MB, running v4.12.5 5f1ec77 currently.
