### ISSUE TITLE
NSIS installer crashes

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#433]
electron-mail-4.12.6-windows-x64-nsis-installer.exe just crashing if I try to run it on my system (Win7 SP1 x64 ESU updates included) Also maybe consider adding zip or 7zip package for Windows. Installer is not needed and I've been anyway unpacking that with 7zip and copying manually for years.

**Comment by ask2018** [comment]
Hmm this is odd. It's crashing only if version 4.12.5 is running. If I update to 4.12.6 and then try to run the installer, it's not crashing.

**Comment by vladimiry** [comment]
The `electron-mail-4.12.6-windows-x64-nsis-installer.exe` installer was tested before releasing on some Win 10 system and worked well.

> Also maybe consider adding zip or 7zip package for Windows. Installer is not needed and I've been anyway unpacking that with 7zip and copying manually for years.

This will be won't fix. You think the installer is not needed but it does some things an average user might miss to do. Like installing the `Microsoft Visual C++ 2015-2019 Redistributable` if needed, forming proper desktop shortcut (it has some CLI args and also proper "app id" so @electron desktop notifications work well, etc). So I'm not going to add support for "zip or 7zip" formats since shipping the app in such distribution format might hurt the experience of an average user which also might cause an additional maintenance burden (like a new invalid issue placed here).

**Comment by ask2018** [comment]
I thought maybe as an additional package for power users, but ok understand. I have actually no problem to unpack the installer with 7zip and copy manually as before. Only reason why I mentioned it here was the crash. I have the crash only if version 4.12.5 is running. If version 4.12.6 is running or program is not running at all, there is no crash. Did you try also that on your testing system?

**Comment by vladimiry** [comment]
> Did you try also that on your testing system?

It was not me who tested the build on Win 10. But I know it normally gets installed just on top existing version (without uninstalling it). The `electron-builder` is responsible for forming the NSIS installer, so if the issue you described is widespread I think it will be spotted there one day, and then fixed.

**Comment by ask2018** [comment]
Just for info to update this. I have no crash anymore with version 4.12.7 when 4.12.6 is running.
