### ISSUE TITLE
Undo/redo support for text-entry

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [vladimiry/ElectronMail#439]
At the moment, if, while typing up an e-mail, I accidentally <kbd>⌘A</kbd>, <kbd>⌫</kbd>, I'm gonna have a very bad day — there doesn't appear to be any "undo" functionality. (At least, on macOS, neither <kbd>⌘Z</kbd> nor <kbd>⌃Z</kbd> had any effect?)

Even a super-basic MVP undo/redo feature would be very welcome!

**Comment by vladimiry** [comment]
The macOS hotkey-specific issues of might look like super trivial things to fix and some other @electron bases projects might have already went through fixing it (including the way of using some dependency built for this purpose, which I avoid doing unless really necessary) but it's not that simple.

> Even a super-basic MVP undo/redo feature would be very welcome!

At the time I was enabling the context menu and shortcuts in the app there was a long-standing issue in @electron which required a workaround for hotkeys to work in the pages embedded in the [webview](https://www.electronjs.org/docs/api/webview-tag) (the way https://github.com/ProtonMail/WebClients gets integrated into the app). Such workaround was simple but sensitive since in some cases triggered the severe app crash on macOS. So, to deal with the issue again, aside from general availability, I will have to run macOS at my side which is not going to happen in the near future.

**Comment by vladimiry** [comment]
Moved to #499.
