### ISSUE TITLE
Captcha error with v4.12.8

### ISSUE THREAD

**Issue by mike2307** [vladimiry/ElectronMail#443]
After updating to the latest flatpak version of electronmail (v4.12.8), the captcha after the login isn't working any more.

Instead of showing the captcha, a new login prompt is being shown. When entering the credentials there again and hitting enter, no action seems to be happening.

See the following screenshot:
![Screenshot from 2021-09-26 22-27-49](https://user-images.githubusercontent.com/29705161/134823169-8dafded2-52a3-4c8c-aa14-8419f9d25583.png)

Help would be appreciated.
Thanks in advance.

**Comment by vladimiry** [comment]
- What the is the `API entry point` value used?
![123](https://user-images.githubusercontent.com/1560781/134823285-de6849bb-9ad4-4592-a42f-d5eff5a77119.png)
- Does reverting to v4.12.7 help?

**Comment by mike2307** [comment]
API entry point is "https://mail.protonmail.com (proton-mail@4.8.0)".

And yes. A downgrade to v4.12.7 helps.
I did it with:
`sudo flatpak update --commit=d699406742de58e061aecdb6539cb4fcb8514c13bb34b84a22536801213898f7 com.github.vladimiry.ElectronMail`

**Comment by vladimiry** [comment]
At the moment @protonmail only supports captcha endpoint for the https://mail.protonmail.com/ `"API entry point"` value, see #419 for details.

According to https://github.com/ProtonMail/react-components/blob/d974f1f4026571e6d4be074f689c5f997f2b700a/containers/api/humanVerification/Captcha.tsx#L5-L11 they were resolving captcha iframe url for captcha `"API entry point"` as https://mail-api.protonmail.com/core/v4/captcha. But it looks like [they recently changed the resoling logic](https://github.com/ProtonMail/WebClients/commit/fc43e8ddd0b79212119ebc05f053e6561c5e166f#diff-2debfe7bb7d7c2f9d2bba32af4e155d0885b324582ee8861e0d4bfe11985ebae) and it now gets resolved as the `webclient0://mail-api.protonmail.com/core/v4/captcha`-like value. So the captcha iframe address was [`API_URL`-based](https://github.com/ProtonMail/react-components/blob/d974f1f4026571e6d4be074f689c5f997f2b700a/containers/api/humanVerification/Captcha.tsx#L6), but now it's [`location.origin`-based](https://github.com/ProtonMail/WebClients/blob/fc43e8ddd0b79212119ebc05f053e6561c5e166f/packages/shared/lib/helpers/url.ts#L162). There is clearly no `webclient0://mail-api.protonmail.com/core/v4/captcha` static page packed into the app and so the app does redirect to the entry/index/login page in this case - this is why you get the login form displayed in the captcha modal.

So it appears that I missed noticing the above-described change doing @ProtonMail web clients stack updating in 2299d9a76acc818112b98e9f9414536773e5e315. It looks like the @ProtonMail client needs to be patched in the way we get previous the behavior captcha resolving behavior, so we get `https` scheme instead of the currently wrongly resolved `webclient0`-like scheme. The bad thing is that it's not so easy to trigger the captcha modal to be displayed at my side for the fix testing purposes, but there should be a way or I could as you @mike2307 to test the fixed/wip-v4.12.9 version when it's ready.

**Comment by mike2307** [comment]
@vladimiry
Yes, sure. I can do some testing as soon a flatpak testing version is available. :+1:

**Comment by vladimiry** [comment]
> flatpak testing version is available

Technically possible but would be a more time-consuming option for me. Any chance you could build deb/pacman package from sources or at least use the deb/pacman compiled at CI system?

**Comment by mike2307** [comment]
I only have access to fedora based systems. So I would need a flatpak, rpm or the AppImage in worst case.
Otherwise someone else with a debian/ubuntu system should volunteer for testing...

**Comment by vladimiry** [comment]
Ok, the rpm & appImage should be available first and then maybe flatpak on "beta" branch too but a little later.

**Comment by vladimiry** [comment]
I've briefly tested the [WIP fix](https://github.com/vladimiry/ElectronMail/commit/9941d53374ca50a09bd73af182ad01b21ec9e9d6) and the captcha worked well for the https://mail.protonmail.com/ API endpoint. So now triggering the pacakges building on CI system.

**Comment by vladimiry** [comment]
The `rpm` package and instruction how to install & run flatpak beta build is shared here https://github.com/vladimiry-playground/electron-mail-issue-443 for testing. The flatpak beta has not yet been update in the remote repository (I guess it will take some time).

**Comment by vladimiry** [comment]
> The flatpak beta has not yet been update in the remote repository (I guess it will take some time).

The possible workaround (while it's not yet listed in `flatpak search com.github.vladimiry.ElectronMail`):
- `flatpak install --user https://dl.flathub.org/build-repo/59051/com.github.vladimiry.ElectronMail.flatpakref` (see `flathub_repo_id` on the https://flathub.org/builds/#/builders/12/builds/7251 page)
- `flatpak run com.github.vladimiry.ElectronMail`

**Comment by vladimiry** [comment]
> The rpm package ...

If needed, the remaining Linux packages shared [here](https://mega.nz/folder/t94GkZrA#VSvkHDNp6SvKuaVJT5FXIg). The related hashes listed in https://github.com/vladimiry-playground/electron-mail-issue-443.

**Comment by vladimiry** [comment]
> I've briefly tested the WIP fix and the captcha worked well for the https://mail.protonmail.com/ API endpoint.

Repeated the test using the release candidate build assembled from the `master` branch and then captcha got displayed. So I'm ok releasing new version.

**Comment by vladimiry** [comment]
By the way @mike2307, consider trying the [persistent sessions](https://github.com/vladimiry/ElectronMail/issues/261) feature so you don't face the login forms anymore. In this case, the issue would remain unnoticed for a longer period though. Ideally, I would enable the e2e test scenario for the captcha case but I'm not ready to jump into dealing with this stuff yet (for testing purposes, there needs to be a way to trigger the captcha scenario in 100% of cases which I'm not aware of not being a proton team member).

**Comment by mike2307** [comment]
@vladimiry 
Wow, this has literally been fixed over night. :+1: 
I just tried the flatpak version from the flathub beta channel and it works perfectly fine again.

**Comment by mike2307** [comment]
@vladimiry 
Just one note:
This should be soon be moved to the stable channel because users will get updated eventually to the broken v4.12.8 version otherwise.

**Comment by vladimiry** [comment]
>  I just tried the flatpak version from the flathub beta channel and it works perfectly fine again.

Except for that it/beta-build has cut out spellcheck functionality (it was easier for me to make the beta build this way, see the [commit](https://github.com/flathub/com.github.vladimiry.ElectronMail/commit/d9722ecbb3b762c3ca9af1a34fdac70060326d77)).

> This should be soon be moved to the stable channel because users will get updated eventually to the broken v4.12.8 version otherwise.

Sure, the "stable" update has already been committed https://github.com/flathub/com.github.vladimiry.ElectronMail/commit/c16b12430f395f6fe3a7f1ceff9af2b9e5e3506f. After the commit happened, it normally takes some time for the update to be available for users (I guess something like 6-12 hours). I guess the "flathub" might offer a way to speed up update propagating but I'm not aware of it. Use the `flatpak search com.github.vladimiry.ElectronMail` to see if it's already available or just refresh the https://flathub.org/apps/details/com.github.vladimiry.ElectronMail page.

**Comment by vladimiry** [comment]
> After the commit happened, it normally takes some time for the update to be available for users (I guess something like 6-12 hours). I guess the "flathub" might offer a way to speed up update propagating but I'm not aware of it.

https://github.com/flathub/flathub/wiki/App-Maintenance#automatic-publishing-delay

> The default is to publish successfully built (non-test) builds after 3 hours.

but could be changed in https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/master/flathub.json via the `publish-delay-hours` value.
