### ISSUE TITLE
Add tor browser fingerprints to browser identity 

### ISSUE THREAD

**Issue by ew0k** [vladimiry/ElectronMail#446]
Hi i think its great this app adds ability to disguise itself as a different browser. It's worth noting that on the Tor network it is highly irregular for a user to be using anything other than a tor browser user agent. they are pretty standardized for purpose of not letting anyone stand out. i think it should be an option to use tor browser fingerprints only especially when setting up an account that accesses protonmail over its tor hidden service. as i said in opening statement using other browser identities is highly irregular, attracts attention and makes a user more unique all things that mute the value of using tor in the first place.

**Comment by vladimiry** [comment]
The browser's "user agent" header rotating feature is available here since [v4.5.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.5.0), see https://github.com/vladimiry/ElectronMail/issues/273#issuecomment-612386163 for details. It's not a per-account thing though at the moment, ie the user agents list is a pool that all the accounts with enabled feature randomly extract the value from. When the pool/list is empty it gets renewed.

**Comment by vladimiry** [comment]
The issue is treated as sorted out.
