### ISSUE TITLE
Electronmail sign-up refuse on macosx El Capitan ver. 10.11.6

### ISSUE THREAD

**Issue by Ichtyosaurus** [vladimiry/ElectronMail#449]
When installing Electronmail desktop client from vladimiry, the application is firing up without problems. However sign-in stucks after password fill-in and clicking on the sign-in button shows a spinning wheel (tiny) in that button and this was in short time visible and then stops. Logging in by protonmail goes no any further (stagnate and locked). So I think that there is a sort of recognize mechanism by protonmail who denied the macosx operating system. So your application is not applicable for macosx ver. 10.11.6 due.

**Comment by vladimiry** [comment]
- There is no support for the macOS systems older than 10.13 High Sierra as this is the older system the CI system is running. This is a sort of important restriction since if you run the released package (not assembled from sources as your own package) a native modules get compiled on 10.13 High Sierra system and so there is no guarantee that 10.11.6 will support the binaries compiled on 10.13 (binary-code compatibility matter). Although it doesn't appear that the binary incompatibility issue is taking place here.
- The app comes with the same source code and same static @protonmail web clients stack for all the released packages. So the issue you posted is likely related to @protonmail itself.

So closing the issue as an upstream one.

**Comment by Ichtyosaurus** [comment]
Ok! That's what I already suspected. Tnx fr reply Vladimiry. It's indeed a ProtonMail issue.

greetz Ralph
