### ISSUE TITLE
Accessing Protonmail content searching

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#466]
Protonmail recently adopted a feature allowing users to search email content. Is there any way to access this feature via Electron Mail?

**Comment by vladimiry** [comment]
Protonmail content searching feature is explicitly disabled in the app since. It won't make sense to enable it here as @protonmail stores the index in the browser's "local storage" but the app by design keep all the browser-specific in memory only. So if you enable @protonmail content search in the app then on the next app start @protonmail will start downloading and indexing all the mails from scratch as the storage is empty.

By the way, the app comes with full-text search since [v2.2.0](https://github.com/vladimiry/ElectronMail/releases/tag/v2.2.0) and `"unlimited"`/code-based search since [v4.11.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.11.0).

**Comment by vladimiry** [comment]
> the app by design runs all the browser-specific storages in the in-memory mode only

There is no plan for changing this logic.
