### ISSUE TITLE
Failed to resolve "webclient1://mail.protonmail.com/images/spacer.gif" resource

### ISSUE THREAD

**Issue by dhbtfs** [vladimiry/ElectronMail#472]
Hi there,

I am getting this error every now and then, red big banner on top of page of my email.  
Can you please clarify if this is a bug or something?

Thanks

**Comment by vladimiry** [comment]
What are the reproduction steps (could not reproduce it)?

I was not able to locate `spacer.gif` in https://github.com/ProtonMail/WebClients.

**Comment by dhbtfs** [comment]
![Screenshot 2021-12-14 001811](https://user-images.githubusercontent.com/95389975/146066649-ad7da9e0-9cf1-4e61-be2d-7bd34d89fff3.png)
![Screenshot 2021-12-14 193242](https://user-images.githubusercontent.com/95389975/146066978-56014416-a743-4cd0-a305-651cb6c50811.png)

When I open an email with allow images to be loaded, I get this error.
Using latest version,

**Comment by vladimiry** [comment]
Thanks for the details. The issue is still reproducible at my side.

- Do you face this error message opening any email regardless of the sender or do you get the error for specific emails only (like only for an email from ICloud)?
- If there is no private information, consider forwarding the email message you tested the issue on to the email specified in the "author" section of the [package.json#](https://github.com/vladimiry/ElectronMail/blob/master/package.json#L5) file.

The blind guess is that you get the error for specific html emails only where the `spacer.gif` image is embedded with a relative address rather than a full address with the domain. The guess is based on the point I posted before:

> I was not able to locate `spacer.gif` file nor references to it in https://github.com/ProtonMail/WebClients.

**Comment by dhbtfs** [comment]
Not only from iCloud. I also get the error when I open Humble Bundle. This is a relatively new account and I get few emails and I delete emails regularly. So far, only checked those 2 I have now.    
I will forward those emails right away to you.

**Comment by vladimiry** [comment]
Thanks for sending a problematic email for review. The guess I posted above, about using image with relative address in the HTML email content was correct as the receive email contains images with `src="images/spacer.gif"` address. So the problem in fact lies at the Humble Bundle side as they form email content in a sloppy way (relative images use).

So the app works as designed. What I could do here is to stop showing the error message to a user in the cases like (done in https://github.com/vladimiry/ElectronMail/commit/7cab9cc13361d0aa4b6797c54175468e82b6cbc3). The new app version won't annoy you anymore.
