### ISSUE TITLE
Attachments bug

### ISSUE THREAD

**Issue by RobertKirchner9** [vladimiry/ElectronMail#480]
Dear Vladimir,

I'm running Linux Mint Mate 20.3. As of yesterday, I noticed a problem with downloading or adding attachments to email messages within ElectronMail. First of all I  can't navigate to anything but my Home folder (I'm given the option in the dialogue window to choose Desktop but clicking it has no effect.) Second, if I try to download an attachment to my Home folder, nothing shows up. If I try to add an attachment to an email, the navigation window doesn't 'see' any files in the Home folder. I can download or add attachments just fine through Protonmail's web interface however.

**Comment by vladimiry** [comment]
Looks like you are running [Flatpak app installation](https://github.com/flathub/com.github.vladimiry.ElectronMail). If so then the described behavior is [by design](https://github.com/flathub/com.github.vladimiry.ElectronMail/blob/5b0678aadcdc7f4ad907e89800ffa05be1677bd2/com.github.vladimiry.ElectronMail.yaml#L13): only the "download" folder is exposed to the app (security improvement via forbidding access to an entire filesystem). You could extend the filesystem access using https://flathub.org/apps/details/com.github.tchx84.Flatseal if needed.

> As of yesterday, I noticed a problem with downloading or adding attachments to email messages within ElectronMail.

The app doesn't update itself nor the [protonmail web clients](https://github.com/ProtonMail/WebClients/) (as embedded  into the app as a static resource). So apparently something has changed in your system.

**Comment by RobertKirchner9** [comment]
Thanks! I deleted the flatpak and reinstalled the deb package and that solved the problem.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
