### ISSUE TITLE
MacOS tray icon is now too big

### ISSUE THREAD

**Issue by quarkl8** [vladimiry/ElectronMail#505]
The tray icon in MacOS is now too large and still has a pixelated edge. It now stretches from the very top to the very bottom of the menu bar and doesn't match the other icons at all.
<img width="1440" alt="Screen Shot 2022-04-17 at 12 03 56 PM" src="https://user-images.githubusercontent.com/100106421/163728868-53efcfc6-38a5-4d25-9783-ac0533027791.png">
How do other apps make their tray icons look clean-edged? Do they use a vector image?

**Comment by vladimiry** [comment]
I guess it depends on the system version. In #199 the "16x16 => 22x22" tray icon size increase was confirmed as an improvement on macOS 12.3 and so the new app version adopted the change.

>  How do other apps make their tray icons look clean-edged? Do they use a vector image?

Other likely use static images. The app builds a final icon using 128x128 size (adds unread indication, changes the color, etc) and then for macOS downscales it to 22x22 using Lanczos algorithm. Btw on Linux 128x128 icon size is used, the tray panel downscales as needed, and a final icon looks well in the tray.

**Comment by vladimiry** [comment]
It won't be too hard to add the icon size option in the app settings. But I'd like to avoid doing this.

> Look like it depends on system version used.

@quarkl8 so what is your OS version?

**Comment by quarkl8** [comment]
> @quarkl8 so what is your OS version?

I'm running the latest Monterey, version 12.3.1. I'm on a 2015 Retina if that matters.
Also, thank you so much for creating this app, i'm complaining right now but it's really generous of you to be working so hard on it. I'd definitely donate to you if I had any money.

**Comment by quarkl8** [comment]
> Other likely use static images. The app builds a final icon using 128x128 size (adds unread indication, changes the color, etc) and then for macOS downscales it to 22x22 using Lanczos algorithm. Btw on Linux 128x128 icon size is used, the tray panel downscales it if needed, and the final icon looks well in the tray.

Is there a reason that using a static image for ElectronMail's tray icon wouldn't work?

**Comment by vladimiry** [comment]
> Is there a reason that using a static image for ElectronMail's tray icon wouldn't work?

For example, dynamic data on the icon (like unread counter, etc). Another reason is that I'd like the code logic to be the same for all systems. Like I said before, a Linux system is able to consume 128x128 icon and then downscale it if needed without breaking the sharpness, but macOS appears not to be smart in this case.

Anyway, I still have no idea what are the tray icon size standards on the macOS system. For some users 16x16 work better but for other 22x22. Let's see what other macOS users have to say. If we don't settle on a specific icon size, I might have to add the respective option in the app settings.

**Comment by vladimiry** [comment]
Tray icon size customization is going to be available in the next release:

> - Enable support for tray icon size customization (#505). This should help with solving a rare case when the app tray icon stands out by its size from the rest of the tray icons.
  ![tray-icon-size](https://user-images.githubusercontent.com/1560781/164544462-8526abce-425a-4002-adb8-02192eb744ba.png)

**Comment by quarkl8** [comment]
Great, thanks @vladimiry!

**Comment by macbugs** [comment]
> **How do other apps make their tray icons look clean-edged? Do they use a vector image?**

> **Look like it depends on system version used.**

I believe you can only use SVG if the OS platform is 10.15 +

> **I'm on a 2015 Retina if that matters.**

ah, ok... I do not have access to retina displays so I apologize for missing this issue.  The icon reference document which I cited earlier was evidently for standard displays so I guess the 22 pixel limit on menu bar icons is multiplied by 2 on retina displays.  If we neglect to specify high resolution equivalents for each icon size in the package, it appears that Mac OS will stretch the bitmap by 2x without interpolation, and this is obviously undesirable.  The solution is expressed here:

**[Append a suffix of “@2x” to your @2x image names, and insert them into @2x fields in the asset catalog of your Xcode project.](https://developer.apple.com/design/human-interface-guidelines/tvos/icons-and-images/image-size-and-resolution/)**

> **The tray icon in MacOS is now too large**

This is subjective: it would not stand out if you had many large icons.  And you need these large icons in case some dysfunctional application or service starts filling up your SSD (or consuming excessive system resources).  The ability to monitor system resource usage in real time is more important than matching the size of the native menu bar icons.  Do you really think this looks bad? 😁

![menubar2](https://user-images.githubusercontent.com/101867641/167787072-f1210ebe-0357-479b-83d1-e9d1ed0c9abc.png)

Mac OS logs absolutely everything which occurs on the platform even when it is not needed for diagnostic purposes — including which application window the user selects with the mouse.  This excessive logging is now showing up as rapid degradation of the (non-replaceable) SSD:

Many of the system daemons (and all iCloud-enabled applications) are constantly logging & reporting mundane user activities to Apple servers even when no iCloud account exists on the machine — and if you search for the name of those services you will find countless reports of excessive system resource usage due to bugs in the source code or the blocking of unnecessary traffic (which is a type of “unhandled exception” that Apple developers frequently do not account for.)

Mac OS has become so dependent on constant internet access that some system services can malfunction if the machine is online but data transmission is prevented by a firewall.  Many people are working on ways to [disable non-essential services](https://gist.github.com/pwnsdx/1217727ca57de2dd2a372afdd7a0fc21), but that is beyond the scope of this discussion.

When the icon size of ElectronMail is reduced, the [new message counter](https://github.com/vladimiry/ElectronMail/pull/503#issuecomment-1098007960) is also reduced to the point where it becomes illegible.  There are hundreds of apps that employ larger menu bar icons — including apps which display charts & graphs (Stats & MenuMeters), most clock & calendar apps (World Clock), various VPN clients & Firewall apps, many Spotlight alternatives (more than 20 apps.)

Sometimes Apple is the greatest “offender” here — for example, you cannot disable the native Mac OS menu bar clock, so if you want to use a different font on the digital clock you need another app -- but you cannot hide the Mac OS analog clock, and this "large" icon is cropped & asymmetrical.

![clock1](https://user-images.githubusercontent.com/101867641/167803422-45a45fa9-bc57-4d43-b1a3-78fd84bc0dad.png)


Here is the one from "World Clock" for comparison.

![worldclock](https://user-images.githubusercontent.com/101867641/167777584-020e2504-6f4b-47db-a00e-bf34a487debf.png)

...and here is actual size on a standard display.

![2clocks](https://user-images.githubusercontent.com/101867641/167780040-a09ddad6-eb3d-4154-a675-34b04e3c1c66.png)

On iOS, Apple again [violates its own design guidelines](https://medium.com/@krvoller/how-iphone-violates-apples-accessibility-guidelines-6785172eb343), which recommend a minimum contrast ratio of 4.5:1 between the text and background colors. In the iMessage application, the white text in a blue bubble has a 3.5:1 contrast ratio, but the white text in a green bubble on messages from Android users has a 2.1:1 contrast ratio, which is _less than half the recommended minimum_.  On some versions of iOS, the ratio is 1.83. (The international "accessibility" standard requires a minimum contrast ratio of 3.0).

Even those with good vision may experience eye strain when reading [text messages from Android users](https://www.techdirt.com/2015/02/12/green-bubbles-how-apple-quietly-gets-iphone-users-to-hate-android-users/) and [resent the person messaging in that color](https://www.androidauthority.com/green-bubble-phenomenon-1021350/).  So I naturally support open source apps & operating systems because the user should have the power to fix things which are [broken by design](https://www.fastcompany.com/3053406/how-apple-is-giving-design-a-bad-name).

> **Btw on Linux 128x128 icon size is used, the tray panel downscales it if needed, and the final icon looks well in the tray.**

With regard to our various discussions in this repo, I want to be perfectly clear that I am not marketing Apple products on github — but some of my clients have purchased Mac hardware due to a [shortage of Intel components](https://www.cnbc.com/2022/04/29/semiconductor-shortage-intel-ceo-says-chip-crunch-to-last-into-2024.html), and I still have to use Macs for development or tech support work.  I support the development of cross-platform applications that provide a [migration path to Linux & BSD](https://www.lifewire.com/linux-on-the-m1-is-already-beating-apple-at-its-own-game-5223390) because we should not become dependent on a single hardware vendor.  But there are many off-grid users with solar or wind power who need to reduce energy consumption, and the energy efficiency of the M1 platform is exceptionally good.  The M1 CPU has motivated other manufacturers to develop products which can match the energy/compute performance ratio of Apple silicon, and this demonstrates how competition benefits the consumer.

![](https://cdn.wccftech.com/wp-content/uploads/2022/02/FL1mNiuWYAMBBr-1-1.jpg)
https://www.digitaltrends.com/computing/intel-arrow-lake-to-rival-apples-best-laptops/

![](https://cdn.wccftech.com/wp-content/uploads/2016/09/2015_InvestorMeeting_Bill_Holt_WEB2-page-022.jpg)

![](https://mspoweruser.com/wp-content/uploads/2018/08/ARM-vs-Intel-Performance-roadmap.jpg)
https://www.techspot.com/news/88034-microsoft-rumored-developing-own-custom-arm-chips-servers.html

**Comment by macbugs** [comment]
According to the Mac OS documentation, supporting Retina displays will require scaling the original (1024-pixel) source image to 10 different sizes.  But when I looked at the source image, I found that the current stock icon is slightly asymmetrical and has a white fringe that shows up on dark backgrounds at high resolutions.  So I decided to make some new icons.  I now have a set of 6 light & dark flat icon themes in neon/fluorescent style, compiled in Mac .ICNS format, including support for Retina displays, with preview catalog using standard Mac menu bar background colors:

![Preview (dark)](https://user-images.githubusercontent.com/101867641/168911107-f19b6909-272f-43d0-a6e5-dad49b45684f.png)

These icons are designed to maintain contrast & minimize distortion at low resolutions when using the Lanczos algorithm.  For cross-platform compatibility and various other purposes, I provide anti-aliased source images for each theme in .PNG format.  For programatic color selection I include the same icon without color & anti-aliasing.  I also made an experimental photo-realistic icon set (but then you could not change the color, so it would only work in the Finder & Dock.)

![gitshow](https://user-images.githubusercontent.com/101867641/168911698-bc6ff4e0-0f9b-47ab-a401-983ed1c468f9.png)

`@vladimiry`:  if you want any of these icon assets, please indicate where I should upload them.
___
The menu bar icon color control is a nice thing to have, but the icon size control does not work here (not that I need it to, 😉 --just wanted to report the issue.) 
`@quarkl8`, does this size control really work on your platform?

**Comment by vladimiry** [comment]
@macbugs, thanks for the research and icons proposal, but I don't think I'm going to change the current icons handling way in the app until I get a macOS device to independently test stuff (not happening in the near future).

**Comment by macbugs** [comment]
ok, no problem --I also used this as an excuse to test some design tools & filters... but in case you still need this information I provide the specifications:  

> **I still have no idea what are the tray icon size standards on the macOS system.**

- [_"The height of the Mac menu bar has grown a little over time, starting at 19pt on System 1, growing to 21pt for the Mac OS X beta, then 22pt in Yosemite, and 24pt in Big Sur.  Those sizes are in points, where 1 point is equal to 1 non-Retina pixel and 2 Retina pixels. Despite the variation in possible menu bar heights, the working area for menu bar extras is fixed at 22pt."_](https://bjango.com/articles/designingmenubarextras/)

- [_"Catalina’s toolbar icons are five pixels smaller than the new icons in Big Sur and Monterey.  In Catalina, the standard size of a toolbar icon was 19 x 19px.  In Big Sur & Monterey, it’s 24 x 24px."_](https://www.sketch.com/blog/2021/10/14/how-we-redesigned-our-toolbar-icons-for-big-sur-and-monterey/)

- [_"If you use an image smaller than 21px, Mac OS X will vertically centre it, but it will be aligned on a pixel boundary."_](https://alastairs-place.net/blog/2013/07/23/nsstatusitem-what-size-should-your-icon-be/)

- [Vector images look bad in the menu bar](https://stackoverflow.com/questions/64901996/correct-icon-size-for-big-sur-preference-panels)

- [Apple document icon specifications](https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/document-icons/)

- [Optimizing for High Resolution](https://developer.apple.com/library/archive/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html)

- [Apple icon image format - file structure](https://en.wikipedia.org/wiki/Apple_Icon_Image_format)

**Comment by quarkl8** [comment]
> The menu bar icon color control is a nice thing to have, but the icon size control does not work here (not that I need it to, 😉 --just wanted to report the issue.)
@quarkl8, does this size control really work on your platform?

Yes, size control works just fine!
