### ISSUE TITLE
14.4.0 regression and temp node file

### ISSUE THREAD

**Issue by ask2018** [vladimiry/ElectronMail#506]
With version 14.4.0 I have again this old issue https://github.com/vladimiry/ElectronMail/issues/5
This time the file is created inside C:\Users\USERNAME\AppData\Local\Temp folder.

**Comment by vladimiry** [comment]
Looks like the `msgpackr-extract` might be that one "not unpacked" module since it appears that this module recently switched the compiled native bundle placing location in the `msgpackr-extract => msgpackr-extract-<platform>-<arch>` way without bumping a major version, and so I didn't make the respective update in the [electron-builder.yml](https://github.com/vladimiry/ElectronMail/blob/075a8aca0fe52bd8608ee216a2f5f28ca4220331/electron-builder.yml#L23) which ended up with "not unpacked" `msgpackr-extract-<platform>-<arch>` module comes into the final app build.

> This time the file is created inside C:\Users\USERNAME\AppData\Local\Temp folder.

Can you share this file? So I know for sure that this is the `msgpackr-extract` related issue.

**Comment by ask2018** [comment]
Yes seems to be that. Here is the file: https://file.silentsilas.com/eWn.node

**Comment by vladimiry** [comment]
Thanks. Preparing a test build with unpacked `msgpackr-extract-<platform>-<arch>` stuff, so the guess could be tested in action.

**Comment by ask2018** [comment]
Ok thank you.

**Comment by vladimiry** [comment]
Can you test [this](https://mega.nz/folder/R8oHgLTL#kbX8BpdYMoz70GymfBfOPA) build?

**Comment by ask2018** [comment]
Seems to be fixed. Thank you.

**Comment by vladimiry** [comment]
Thanks for placing the issue and testing the fix. The issue confirmed to be the [msgpackr-extract](https://github.com/kriszyp/msgpackr-extract/commit/69ab855500cf91fd545c1e414c86b1943974f230) update related.
