### ISSUE TITLE
Whitelist new storage URL for ProtonDrive

### ISSUE THREAD

**Issue by jeifour** [vladimiry/ElectronMail#508]
![スクリーンショット 2022-04-22 12 50 15](https://user-images.githubusercontent.com/3247063/164701454-d89210da-399a-4c90-a571-d8406993c34f.png)

Using ElectronMail 4.15.0 to access ProtonDrive through the Tor endpoint, I'm getting this error message.

**Comment by vladimiry** [comment]
The workaround is obvious: disabling the `Block non "API entry point"-based network requests` feature for the account (disabled by default).

**Comment by vladimiry** [comment]
I ended up whitelisting the `*-storage / storage`-like subdomains of the selected API entry point since there were reports of the `fra-storage` and `zsh-storage` subdomains to be used.

By the way, the next app release comes with only proton.me (new one) and Tor API entry points since https://mail.protonmail.com and https://app.protonmail.ch addresses are now deprecated by @protonmail for use as API addresses (confirmed by their engineering team).
