### ISSUE TITLE
Add mail.proton.me as API entry point

### ISSUE THREAD

**Issue by quarkl8** [vladimiry/ElectronMail#518]
The only API entry point available right now is the old one, mail.protonmail.com. Of course I think keeping it for people who prefer the old design is a good idea, but I personally prefer the redesign, so could you add the new URL in the next update? Thanks!

**Comment by vladimiry** [comment]
A huge rework is already close to completion, see https://github.com/vladimiry/ElectronMail/commit/2599f1d26dd32a7fb7e0e10222abfad6e587eece.

See the next/v.5.0.0 release changelog draft if interested:

 - Upgrade packaged in the app Proton web clients to the recently rolled out [v5 stack](https://proton.me).
  - Used in the previous app versions, https://mail.protonmail.com and https://app.protonmail.ch API entry points got deprecated by Proton and so now replaced in the app with a new https://proton.me based address. Used before Tor API entry point is still valid.
  - The `settings.bin` and `session.bin` files produced or modified by v5.0.0+ app versions won't be compatible with prior to v5.0.0 versions (only the backward compatibility is respected). So if you practice downgrading the app version, it's recommended to backup the app data files (all the files produced and modified by the app listed in the [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ), see point `#2`).
- Fix the [local store](https://github.com/vladimiry/ElectronMail/wiki/FAQ) view mode availability in the offline mode. The issue was reported by @macbugs in an unrelated discussion.
- Whitelist Proton's "storage" subdomain (#508, https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619).
- Significantly reduce installation packages size.
