### ISSUE TITLE
Switching between online/db views at login page bypasses security check

### ISSUE THREAD

**Issue by ellylldhan** [vladimiry/ElectronMail#530]
Using electonmail 5.1 on Win10 

In online view, I am asked to prove that I am human when I enter my credentials (the popup is blank by the way, no captcha visible).

if I close the modal and click on the wrench icon to toggle database view, I end up on my mail box where I can see all my mails without having to pass security check.

If I click on the database icon again, I go back to online view login page that show me as not connected.

**Comment by vladimiry** [comment]
This is an intended behavior. The "local store" related data by design has to be available in the offline mode, so there is no need to sign in into the mail account but into the app using a master password.

> the popup is blank by the way, no captcha visible

This is a separate issue. Can you enable the highlighted `Block non "API entry point"-based network requests` toggle for the mail account and try again? I'm interested to reveal what is the captcha iframe address and that toggle might potentially shed some light to this point.
