### ISSUE TITLE
New UI Icons Are Too Confusing

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [vladimiry/ElectronMail#572]
I keep mixing up the "mark as read/unread," "archive," and "move to [folder]" buttons when I didn't use to do that in earlier versions. Is there any way of changing the icon set? Actually, there's a severe lack of accessibility settings for this app...

**Comment by vladimiry** [comment]
It's given by @protonmail, obviously, so sort of upstream issue.

But if you are ready to deal with CSS, the "Custom CSS" feature is available since [v4.10.0](https://github.com/vladimiry/ElectronMail/releases/tag/v4.10.0), which might be helpful in some cases. The respective CSS edit block located on the account edit form, so it's per account option.

**Comment by vladimiry** [comment]
Another option to tweak proton's UI is to apply your own [patches](https://github.com/vladimiry/ElectronMail/tree/master/patches/protonmail) to their web client. In this case you will have to assembly the app package from the sources.

**Comment by neurodiverseEsoteric** [comment]
I have no idea how to use css...

**Comment by vladimiry** [comment]
The way to modify the proton's UI is provided by the app (custom CSS injection). Using the feature is up to a user. This project is not a place to provide/maintain specific proton UI tweaking CSS code snippets. You could try looking some ready-made custom CSS proton themes on the internet.
