### ISSUE TITLE
Questions about using with TOR entry (image proxy, other connections)

### ISSUE THREAD

**Issue by TimmyBoi155** [vladimiry/ElectronMail#593]
Want to say firstly thank you for this application. It's amazing. Even if proton comes out with a desktop client, i will likely keep using this one.

I want to use this over TOR. But I have a few questions about it:

1. If I use the TOR API, how are images loaded through proton's image proxy? Do you merely use the clearnet URL but through the TOR network? or does proton have an onion based image proxy?
2. If I have 2 accounts connecting over tor, can they be correlated to each other in any way that you are aware of? Locally-speaking. Also, does each TOR account have individual tor circuits? 
3. Are there any other connections that are made by the webclient besides these? and are they requested over TOR?

Thanks in advance

**Comment by TimmyBoi155** [comment]
Also, I'm currently having an issue, where, if I try to log in under the TOR API, the "Log In" button loads for 1 second, then stops loading, and nothing happens. It just stays at log in. However, it works fine under proton.me

**Comment by vladimiry** [comment]
Proton uses `core/v4/images` API call to load remote images. The address depends on the API entry point you selected in the app on the account edit form. There was an issue with API address resolving in recent app versions, but got fixed in v5.1.6.

Btw, enabling [Block non "API entry point"-based network requests](https://github.com/vladimiry/ElectronMail/issues/312#issuecomment-709650619) flag on the account edit form supposed to block non-API entry point based requests. The hcaptcha.com domain is kept in the whitelist.

> I'm currently having an issue, where, if I try to log in under the TOR API, the "Log In" button loads for 1 second, then stops loading, and nothing happens.

It worked before, so apparently proton changed something at the backend side (like for example API subdomain use schemes). So I put it as an upstream backend-related breaking change.
