### ISSUE TITLE
v5.1.5 all accounts need log in again

### ISSUE THREAD

**Issue by qupig** [vladimiry/ElectronMail#595]
It seems that after updating to v5.1.5, the login status of the accounts is lost, and all accounts need to log in again.

Logging back into multiple accounts was a pain and we had a lot of Captcha to complete manually.

Is this a problem created by the service provider, or is there a way we can avoid it and keep using the old session?

If possible, I hope to avoid the need to re-login all accounts as much as possible in the future.

Thank you for developing a very convenient App, open source and free are not easy, you have brought us too much convenience! 🙏

**Comment by vladimiry** [comment]
Proton before [v4](https://proton.me/blog/sso-beta) didn't allow keeping the session between browser restarts, but the app was able to do so before, and it keeps doing it in the same way. Basically, the app saves some `sessionStorage`'s data between browser restarts. In order to do so, session modifying events have to be detected and properly processed by the app, and some implementation imperfections are possible here. Detecting and debugging such kind of imperfections is not easy, but some improvements were made since the original implementation.

The reliable way to keep the account session is using proton's SSO sign in method introduced since v4, same way it works in a regular browser. The thing is that the app, by design, doesn't store on the disk any browser's storages, but stores all the sensitive information in a custom way, protected with master password. This is why, for example, content/body search is explicitly disabled in the app, see #466. I'm not going to switch to a regular browser storage in the near future.

Proton might open its electron-based desktop client soon, at least for beta testing, so then you might it more suitable for your needs.
