### ISSUE TITLE
2FA dont work with update of proton.me

### ISSUE THREAD

**Issue by xyz-nobody** [vladimiry/ElectronMail#626]
Before, the 2FA filled itself,

Now I have to do a captcha and it's blocked on all my 2FA.

Is it easy to extract Two-Factor secret key via the interface?

![Screenshot from 2023-07-25 18-17-35](https://github.com/vladimiry/ElectronMail/assets/6586244/d658d60f-c68c-4bf6-a98b-5234b276f898)

**Comment by vladimiry** [comment]
There were multiple reports that recently, at least since the last few months, @protonmail started troubling users with excessive user verifications. The guess is that they started doing that for users who use multiple free accounts. Also, according to some Reddit posts, it looks like they started banning accounts. I personally don't recommend using multiple free accounts.

It's unclear why 2FA being asked each time. Do you have "Persistent session" option enabled for the accounts? The respective toggle located on the account edit form.

> Before, the 2FA filled itself,

Do you still use the obsolete "Accounts Credentials" feature? There is no automated e2e test for verifying the auto forms filling feature, and I don't test it manually since it's obsolete. Read it as unsupported. So if @protonmail changed login/2FA forms-related HTML code, the autofilling might be broken in recent app releases. The "Accounts Credentials" feature is obsolete for a long time. I recommend removing the credentials saved in the app (make sure you saved them somewhere else though or got it well-remembered) and using the above-mentioned "Persistent session" feature for auto login into the accounts. The obsolete "Accounts Credentials" feature is going to be dropped at some point.

**Comment by xyz-nobody** [comment]
How can I save my TOTP code?

I put it in the application but I can't remember it (same for the password).

**Comment by xyz-nobody** [comment]
i found this, and yes i use obsolete Account Credential (Its very old account)

The credentials stored encrypted in the settings.bin file located in the [settings folder](https://github.com/home/amnesia/.config/electron-mail). See [FAQ](https://github.com/vladimiry/ElectronMail/wiki/FAQ) for details.

How can I open settings.bin to find the credentials inside?

**Comment by vladimiry** [comment]
https://github.com/vladimiry/ElectronMail/issues/318

**Comment by vladimiry** [comment]
Closing as resolved.
