### ISSUE TITLE
issues downloading large files from Drive

### ISSUE THREAD

**Issue by TimmyBoi155** [vladimiry/ElectronMail#638]
I am trying to download a file that is a bit over 2 GB, and I get this message from proton drive:

"Browser might run out of memory
Your current browser does not support the downloading of large files due to the unavailability of service workers. Downloading large files may freeze or leave the browser unresponsive. Please use the latest versions of a [recommended browser](https://proton.me/support/recommended-browsers) and try again."

I tried to download it anyway but when i save the file to a directory after it downloads, it does not show up in the directory.

I looked around for an issue for this but couldnt find one, so I apologize if one was already made

**Comment by vladimiry** [comment]
Good finding.

There is a [TODO](https://github.com/vladimiry/ElectronMail/blob/8b54e6941c020adbf1a04b4063507bf724d0d059/src/electron-main/protocol.ts#L182-L183) which is not fulfilled yet, and so the recent service worker script location change by @protonmail, which is an issue cause, didn't get automatically noticed.

The issue [got fixed](https://github.com/vladimiry/ElectronMail/commit/bfae0c6f7d56b832cbe17a07af73e69d4440ec36#diff-416103b86e26550a4c72d47fad80167b357b888ff6493f7aef321611d3c9038bR185) in the `wip` branch by bfae0c6. Not sure yet if I will be promptly publishing a new release due to this fix.

Also, [I made sure](https://github.com/vladimiry/ElectronMail/commit/bfae0c6f7d56b832cbe17a07af73e69d4440ec36#diff-0d26ce80e79d03ab0fa696e847e7523367c6dcb2829460ae1249d42e24c4f5ebR333-R348) if service worker script location gets changed again, it gets automatically noticed in the build pipeline and releasing gets blocked until the issue is fixed.

**Comment by vladimiry** [comment]
@TimmyBoi155, can you test the build uploaded [here](https://mega.nz/folder/llA21TRJ#mM5J4qrGPtRjF7sBwDkSgA)? If it runs well, I'm going to publish it as v5.2.1 release.

**Comment by TimmyBoi155** [comment]
sorry for the late reply. yeah will test and get back in a bit @vladimiry

**Comment by TimmyBoi155** [comment]
seems to work great. it did not give me the warning like last time. I downloaded a file over 3GB no issue :) and a 10GB file as well @vladimiry

**Comment by vladimiry** [comment]
@TimmyBoi155 thanks, new release is on its way.
