### ISSUE TITLE
Tutanota: option to automatically load images (like protonmail does by default)

### ISSUE THREAD

**Issue by jeroen7s** [vladimiry/ElectronMail#64]

**Comment by vladimiry** [comment]
This feature has been mentioned as `under review` [here](https://github.com/vladimiry/email-securely-app/releases/tag/v2.0.0-beta.2) at the bottom.

The built-in emails viewer is going to remain simple. Displaying images, as well as making email content look more similar the original content is not a priority at the moment since it can be achieved with the upcoming export feature. Which means importing the exported emails into any email client allows to search and toggle images viewing.

Nevertheless maybe one day we will get to the point of starting enhancing the built-in emails viewer, so let's keep the issue opened.

**Comment by vladimiry** [comment]
Anothe part of the issue is enabling images viewing by default for Tutanota's [WebClient](https://github.com/tutao/tutanota) (ie `online view mode` in terms of the app v2), which I think you are about. This is also not considered as a pritority thing, but I believe can be achieved. Looks like Tutanota itself has not yet even planned enabling the feature https://tutanota.uservoice.com/forums/237921-general/suggestions/8560537-have-an-option-to-automatically-load-images-redes, but I guess it might be part of official desktop app they recently starting to build.

**Comment by jeroen7s** [comment]
completely forgot to respond to this, sorry.
> Another part of the issue is enabling images viewing by default for Tutanota's WebClient (ie online view mode in terms of the app v2), which I think you are about.

yeah this is what i meant in the original post

**Comment by vladimiry** [comment]
Closing due to #180.
