### ISSUE TITLE
Critical error - "A new version of Proton Mail is available."

### ISSUE THREAD

**Issue by gene-fls** [vladimiry/ElectronMail#650]
I have ElectronMail deployed business-scale, and computers are popping up with a native ProtonMail error:
```
A new version of Proton Mail is available. Refresh the page.
```
Clicking "Refresh the page." results in the same error. Emails are not loading or sending, at least not consistently.

**Comment by Praethiax** [comment]
same. bump. basically unusable rn.
sending mails, saving drafts and sometimes loading mails does not work.
right now i can only receive mails.

**Comment by vladimiry** [comment]
It happened several times before. The reason is that ElectronMail by design, for multiple reasons explained before, comes with static [proton web clients](https://github.com/ProtonMail/WebClients) prepackaged with the app, so when Proton introduces breaking changes which require [proton web clients](https://github.com/ProtonMail/WebClients) update, the update has to come with new ElectronMail release. There is no in time update since, you know, it's an unofficial app.

If there will be no unexpected obstacles with preparing the new release, it should come later today, or tomorrow.

The issue like this appears to be a good test to see if someone is using the app at all :smiley:

**Comment by delibdev** [comment]
I also use the app and love it - thanks for your work on it. Hopefully there are not any of the unexpected obstacles you mentioned.

**Comment by vladimiry** [comment]
> Hopefully there are not any of the unexpected obstacles you mentioned.

I don't expect blockers as there is no major version bump at the proton side. The work was huge when that app was switching to "proton web clients" v4 and especially to the current/v5 major version.

What I've already noticed in the current "proton web clients" update, is that they added `isElectronApp()` test function. So they already separate some logic on the web clients based on this function. I made the function always return `false` for the ElectronMail, as it should not pick specific logic they implement for or disable on their work-in-progress Electron-based desktop app.

**Comment by Tman1816c** [comment]
hahahha we all use your app bro and love it so don't worry there is lots of us using it :) look forward to the update

**Comment by TheDcoder** [comment]
Just wanted to chime in and say that this program is one of the most essential things that I run everyday, thank you so much for working on it. Even if Proton released their own electron-based program I doubt it will be as good as ElectronMail!

Thank you so much for working on this @vladimiry, extra credits for the fast updates that you always give us!

**Comment by vladimiry** [comment]
> Even if Proton released their own electron-based program I doubt it will be as good as ElectronMail!

This sounds somehow flattering, but I still struggle to detect in which part, maybe it doesn't :blush:, since there is no official thing yet to compete with :slightly_smiling_face:. It's clear that ElectronMail is not supposed to compete with official app, as they build a for-profit thing for use by an average user, so for a wide user group. ElectronMail has some features the average user won't be needed, so I agree, in a way, Proton thing won't be as good, since there is no goal of implementing niche things for a small/extreme user group. But, after all, Proton thing is going to stay vs ElectronMail, which is likely to be archived when I stop using it. So the general advice is to get prepare yourself for an official app to step in.

**Comment by TheDcoder** [comment]
> This sounds somehow flattering, but I still struggle to detect in which part

It is meant to be, I was praising your work, great design!

> which is likely to be archived when I stop using it.

That will be a very sad day indeed, maybe someone will fork it... perhaps that "someone" might even be me :wink:

**Comment by Bear-Hunter** [comment]
Amazingly important app, I love it. I run it at startup. I hope you manage to find a fix and get an update rolled out. Best to you.

**Comment by varxx** [comment]
I use ElectronMail throughout the day, every day. That's why I get frantic when something doesn't go right (which is pretty much never). Thanks for your work. ProtonMail's web interface is fine, but I soooo much prefer ElectronMail, which gives me the standalone experience that I prefer. Keep up the good work.

**Comment by vladimiry** [comment]
New release is going to fatter than usual. Looks like because Proton has put a lot of BlackFriday-related  promo images into the [proton web clients](https://github.com/ProtonMail/WebClients).

**Comment by TheDcoder** [comment]
Can we cull those images ? I don't think anyone is going to look at BF deals inside ElectronMail.

**Comment by vladimiry** [comment]
> Can we cull those images ? 

Technically yes, but I would not do this. A list of reasons, but the sufficient one is that this would be a one-off thing just for this release, as later after BF they will likely remove those images on their own initiative, so the next app release gets slimmer.

**Comment by TheDcoder** [comment]
Assuming that these black friday assets are segregated into discrete locations, we can exclude them permanently so that they never get into our builds...

But I understand that this is a subjective thing, personally I wouldn't like having those images stored on my SSD.

Some purist folk would obviously prefer the web app to be in a state which is altered as less as possible.

Maybe we can have a vote? Thumbs up if you want to remove images and thumb down if you want them.

**Comment by vladimiry** [comment]
> Some purist folk would obviously prefer the web app to be in a state which is altered as less as possible.

The amount of patching itself doesn't bother me much. But every patch requires effort and increases maintenance burden, and this is what I care about, since in order to keep publicly maintaining this project I have to strike a balance between different matters. Also, it's a blocker here. So, a purist should be able to fork the code and apply needed changes independently.

**Comment by jarrard** [comment]
oofp
Hope a update can be sorted asap. Thanks for the effort, really like this little app, hope it doesn't die due to Proton doing these silly updates to the API.

**Comment by vladimiry** [comment]
> New release is going to fatter than usual.

> this little app

The app takes it as a compliment, and I like the irony. Yes, it's getting fatter, but still remains graceful.

**Comment by vladimiry** [comment]
I briefly tested the new build, including sending email, and it seems to work fine, so v5.2.2 with included fix is now published.

**Comment by varxx** [comment]
Great, just installed 5.2.2 and it's working just fine. Thank you very much!

**Comment by Bear-Hunter** [comment]
Thank you, you are amazing!

**Comment by delibdev** [comment]
thank you @vladimiry! 

(reminder to everyone that's been reading along - make sure you've starred the repo)
