### ISSUE TITLE
@taivlam for the mpr PKGBUILD

### ISSUE THREAD

**Issue by ghost** [vladimiry/ElectronMail#684]
@taivlam
comment notification there doesn't work and your email is a no reply github email address.

I made an improved version of the PKGBUILD, it's renamed, it's a simple pass through for the upstream deb package, it uses sha256 like upstream. I haven't publish it yet.
[PKGBUILD.txt](https://github.com/vladimiry/ElectronMail/files/15147001/PKGBUILD.txt)

For those asking. Indeed, this PKGBUILD doesn't really build a package, it's just a convenience.

**Comment by taivlam** [comment]
Hi @pirate486743186, 

1. Just to be clear, the current `PKGBUILD` is working, correct?  I basically inherited the MPR package after the package hadn't been updated for a while (as in, simply updated the version number to a `PKGBUILD` that's otherwise  working).
2. Right now, I'm not sure what's happening with the MPR, as I receive a "502 Bad Gateway" error when I try to log onto `mpr.makedeb.org`.  A message from the MPR channel on the makedeb Matrix channel indicates there were also issues with the APT repo starting at some point yesterday.
    * So, I can't currently log into the MPR to fix this right now &/or check my changes after pushing the changes.
    * Maybe that explains why I hadn't gotten any MPR comment notifications?
3. If you want, I could make the changes once the MPR is back online and note you as a contributor, once I get the chance to make the changes.
4. When you reference "upstream", do you mean the use of SHA256 sums used in the AUR [`electronmail-bin`](https://aur.archlinux.org/packages/electronmail-bin) package maintained by ElectronMail's developer?
    * I think, unless if somehow ElectronMail was maintained upstream by Debian/Ubuntu &/or a third-party APT repo was made (which would be a miracle pragmatically) and using SHA256 sums is more customary, I would like to keep using [BLAKE2](https://en.wikipedia.org/wiki/BLAKE_(hash_function)#BLAKE2) sums.
    * If performance is really an issue, I'd switch to SHA256.
6. I have a place where I keep track of `PKGBUILD` changes on [GitHub](https://github.com/taivlam/aur-mpr-packages/tree/main/MPR/electronmail-bin) for the MPR's `electronmail-bin`, and anyone can make PR's/create new issues in my AUR/MPR [repo](https://github.com/taivlam/aur-mpr-packages).
7. I can change the e-mail I use for MPR maintenance contact to a SimpleLogin alias, if that would be a line of communication that is better suited to have the option to reply.
    * However, I would like to keep most communications of critical proposed changes (not related to security, such as this) in the public - and currently I don't have anything like a public mailing list for MPR packages I maintain (though that's also probably not completely necessary, either) given the precedent set by the relatively very recent [XZ Utils backdoor](https://en.wikipedia.org/wiki/XZ_Utils_backdoor).  Of course, I don't realistically expect any risk of that caliber for this MPR `PKGBUILD` (hopefully).

Since the MPR is temporarily down, I'll use this time to try to understand your proposed changes, as I'm relatively new to maintaining MPR packages.
