### ISSUE TITLE
Project development

### ISSUE THREAD

**Issue by alfredonodo** [vladimiry/ElectronMail#688]
Hi,
is the project still under development considering that protonmail has released its [official client](https://proton.me/blog/proton-mail-desktop-app)?
Thank you

**Comment by vladimiry** [comment]
Yes, it's under development. Some updates available in the [wip](https://github.com/vladimiry/ElectronMail/commits/wip/) branch.

Currently, the official client, as far as I know, is an @electron wrapper for web client without addition features added. ElectronMail is also a wrapper, but comes with many custom features which aimed to enable enhanced desktop user experience.

A sort of blocker for releasing a new app version, is the fact that Proton [stopped publishing source code](https://github.com/ProtonMail/WebClients/issues/354) of https://github.com/ProtonMail/WebClients since mid-April.

PS Also see #664.
