### ISSUE TITLE
[Bug?] Proton Calendar Error

### ISSUE THREAD

**Issue by 0x89b217** [vladimiry/ElectronMail#697]
When I open ElectronMail, it prompts    **The Calendar has not reached the signed-in stage in 15000ms.**

![Snipaste_2024-09-13_10-26-41](https://github.com/user-attachments/assets/054bb29d-eb80-4082-a4a1-f820b4709504)

**Comment by vladimiry** [comment]
This is caused by the "Desktop notifications for calendar events [experimental] [229](https://github.com/vladimiry/ElectronMail/issues/229#issuecomment-720090933)" feature, which I didn't pay attention in the recent release as that's an "experimental" feature and I think is going to be removed. This feature is an opt-in one (disabled by default). Disabling it should get rid of the error.

![cal-notifier](https://github.com/user-attachments/assets/f57381ab-2f6a-476a-9412-52e46d2d2256)
