### ISSUE TITLE
[Feature Request] Minimize to Tray

### ISSUE THREAD

**Issue by dgsmiley18** [vladimiry/ElectronMail#703]
### Description
I'm suggesting an option in the settings to minimize to tray if you click on the button minimize

### Problem Statement

Email is something private, it's a good suggestion to be able to hide it in the tray to avoid being visible in the taskbar, right now you can only minimize to tray if click on "Close"

### Proposed Solution
To solve this problem, i suggest to create the option in the settings to minimize to tray if the user click on minimize button

**Comment by vladimiry** [comment]
Thanks for the detailed issue description.

If a user has chosen to click minimize instead of close, it's a user's choice. I mean, when I click minimize I want the window to be minimized, not closed nor hidden to the tray. So I see no point to spoil the purity of standard minimize action nor overloading the settings section with a questionable option like this. So in my opinion, implementing this would be against standard UX practices and this is "won't fix" from my side.

>  right now you can only minimize to tray if click on "Close"

Not only by clicking "close". Here are some other ways of "closing to tray":
- By clicking the tray icon, as this action toggles the window visibility.
- Via the respective tray's menu item.
