### ISSUE TITLE
The linux kernel is banning Russian contributors as part of american sanctions against Russia

### ISSUE THREAD

**Issue by pirate486743186** [vladimiry/ElectronMail#704]
Vladimiry is Russian right? If you are Ukrainian... well, oups.

The linux kernel is banning Russian contributors because legally it is established in the US and contributing is considered entering into a contract. github is owned by microsoft so they might do something similar.

I'm not a lawyer and there's alot of uncertainty in what will really happen. Lol, how are they going to enforce this? Regardless, you might get banned from github. The deadline for compliance is in December.

**Comment by vladimiry** [comment]
Thanks for the info. I haven't heard of it until this post. I guess that being blacklisted for anyone, not just Linux maintainers, not for personally doing something wrong, but by a very wide collective criteria, is demotivating at least.

Not Russian and not located there, so that EO doesn't look like applicable to me or this project.

If I get banned regardless, well, there are few options. I either move the projects to some other code hosting platform, or I just keep it for myself without public presence.
