### ISSUE TITLE
cmd of app

### ISSUE THREAD

**Issue by babebort** [vladimiry/ElectronMail#709]
can you explain each cmd?

or do you have page with describe?

` /app/ElectronMail/electron-mail --type=renderer --enable-crash-reporter=ba6f32d9-debb-47fd-9d2d-68ebcbbfb91c,no_channel --user-data-dir=/home/bortnik/.var/app/com.github.vladimiry.ElectronMail/config/electron-mail --standard-schemes=webclient --secure-schemes=webclient --cors-schemes=webclient --fetch-schemes=webclient --service-worker-schemes=webclient --app-path=/app/ElectronMail/resources/app.asar --enable-sandbox --disable-blink-features=Auxclick --js-flags=--max-old-space-size=6144 --disable-databases --lang=en-US --num-raster-threads=2 --enable-main-frame-before-activation --renderer-client-id=4 --time-ticks-at-unix-epoch=-17297091`

**Comment by vladimiry** [comment]
This is something you will have to explore in your own. The direction is @electron, since it's used as a runtime.

**Comment by vladimiry** [comment]
There are some arguments from the listed cmd setting of which gets explicitly triggered by the app:
- `--js-flags=--max-old-space-size=6144` this was increasing max memory use before @electron/@chromium enabled memory compression. As far as I know, it doesn't make much sense these days, but I would need to run some tests before stopping setting this argument and there is no guarantee that it won't make sense again in the future in newer @electron versions. So I tend to keep.
- The arguments with `webclient` value represent enabled custom `webclient` [scheme/protocol](https://www.electronjs.org/docs/latest/api/protocol). This scheme is used in the app for serving static [Web Clients](https://github.com/ProtonMail/WebClients). When things were getting implemented in the app, there were some differences between serving resources from `file://` vs custom scheme, so in order to be able to implement needed features a custom scheme had to be introduced. Not sure if the `file://` scheme still has many limitations in @electron as it was before.
