### ISSUE TITLE
Seleting an email makes the email list scroll to the top

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [vladimiry/ElectronMail#712]
Linux, Flatpak

When I select an email it scrolls up to the top of the list. I can only select mail if it is already at the top of the list view.

https://github.com/user-attachments/assets/b27d7b47-3c31-405e-8d43-533d9c501092

**Comment by vladimiry** [comment]
Thanks for the detailed report.

This is https://github.com/ProtonMail/WebClients mail app on the video, so the issue should be reported to them/Proton, but only if you can reproduce it on proton.me.

The app comes with a static WebClients apps stack, so there is a chance that the issue has already been fixed by Proton, you can test it by performing the same action on proton.me.

Also, there is a work-in-progress app build that comes with a newer WebClients apps stack than is packed into the v5.2.3 release, which is shared in https://github.com/vladimiry/ElectronMail/issues/694#issuecomment-2400871180.
